-- =====================================================================
-- Devhut Stores: extra catalogue (264 products)
-- Run AFTER setup.sql: Supabase dashboard > SQL Editor > New query > paste > Run.
-- Safe to run again (existing ids are skipped). With the sample products from
-- setup.sql every category ends up with 50 or more items:
--   groceries 49, electronics 50, gadgets 49, home 62, fashion 54 (new products only)
-- Products have no photos yet: the store shows a category placeholder until you
-- upload images in Admin > Products.
-- =====================================================================

insert into public.products (id, name, brand, category, price, old_price, rating, reviews, stock, featured, is_new, images, description, highlights, variants) values
  ('long-grain-basmati-rice-5kg', 'Long Grain Basmati Rice, 5kg', 'Golden Harvest', 'groceries', 12.99, null, 3.9, 43, 98, 20, false, '{}',
   'Aged basmati with fluffy, separate grains and a delicate aroma. A pantry staple for pilaf, biryani and everyday meals.',
   array['Aged 24 months', 'Extra-long grains', 'Resealable 5kg bag'],
   '[]'::jsonb),
  ('parboiled-long-grain-rice-10kg', 'Parboiled Long Grain Rice, 10kg', 'Golden Harvest', 'groceries', 17.5, null, 4.5, 12, 89, 21, true, '{}',
   'Firm, non-sticky parboiled rice that holds up in jollof, fried rice and stews.',
   array['Non-sticky when cooked', 'Family-size 10kg', 'Stone-free and cleaned'],
   '[]'::jsonb),
  ('spaghetti-pasta-500g', 'Spaghetti Pasta, 500g', 'Bella Terra', 'groceries', 1.79, 2.38, 4.1, 83, 55, 22, false, '{}',
   'Bronze-cut durum wheat spaghetti with a rough surface that grabs sauce.',
   array['Durum wheat semolina', 'Cooks in 9 minutes', 'Bronze-cut'],
   '[]'::jsonb),
  ('penne-rigate-pasta-500g', 'Penne Rigate Pasta, 500g', 'Bella Terra', 'groceries', 1.79, 2.24, 4.0, 109, 115, 23, true, '{}',
   'Ridged tubes that trap chunky sauces and bakes well.',
   array['Durum wheat', 'Cooks in 11 minutes', 'Holds sauce well'],
   '[]'::jsonb),
  ('whole-wheat-fusilli-500g', 'Whole Wheat Fusilli, 500g', 'Bella Terra', 'groceries', 2.19, null, 4.0, 100, 91, 24, false, '{}',
   'High-fibre wholegrain spirals with a nutty flavour.',
   array['Wholegrain', 'High in fibre', 'No additives'],
   '[]'::jsonb),
  ('rolled-porridge-oats-1kg', 'Rolled Porridge Oats, 1kg', 'Morning Field', 'groceries', 3.49, null, 4.1, 16, 22, 25, false, '{}',
   'Creamy rolled oats for porridge, overnight oats, flapjacks and baking.',
   array['100% wholegrain oats', 'Source of fibre', 'Cook in 4 minutes'],
   '[]'::jsonb),
  ('crunchy-muesli-with-nuts-750g', 'Crunchy Muesli with Nuts, 750g', 'Morning Field', 'groceries', 5.99, null, 4.3, 66, 38, 26, false, '{}',
   'Toasted oat flakes with almonds, hazelnuts, raisins and seeds.',
   array['No added sugar', 'Real nuts and fruit', 'Resealable pouch'],
   '[]'::jsonb),
  ('honey-corn-flakes-500g', 'Honey Corn Flakes, 500g', 'Morning Field', 'groceries', 3.79, null, 4.6, 17, 43, 27, false, '{}',
   'Golden crispy flakes lightly glazed with honey, fortified with iron and vitamins.',
   array['Fortified with vitamins', 'Stays crisp in milk', 'Family box'],
   '[]'::jsonb),
  ('plain-wheat-flour-2kg', 'Plain Wheat Flour, 2kg', 'Millstone', 'groceries', 2.49, null, 4.9, 649, 110, 28, false, '{}',
   'All-purpose flour for bread, pancakes, chapati and cakes.',
   array['Multi-purpose', 'Finely milled', '2kg paper bag'],
   '[]'::jsonb),
  ('self-raising-flour-1-5kg', 'Self-Raising Flour, 1.5kg', 'Millstone', 'groceries', 2.29, 2.56, 4.7, 59, 84, 29, false, '{}',
   'Pre-mixed with raising agent for light, reliable sponges and scones.',
   array['Consistent rise', 'Ideal for cakes', '1.5kg bag'],
   '[]'::jsonb),
  ('granulated-white-sugar-2kg', 'Granulated White Sugar, 2kg', 'SweetLeaf', 'groceries', 2.59, null, 4.6, 58, 43, 30, false, '{}',
   'Fine granulated sugar for tea, baking and everyday use.',
   array['Pure cane sugar', 'Free-flowing', '2kg pack'],
   '[]'::jsonb),
  ('soft-brown-sugar-500g', 'Soft Brown Sugar, 500g', 'SweetLeaf', 'groceries', 2.19, null, 4.6, 358, 29, 31, false, '{}',
   'Moist brown sugar with a caramel note for cookies, cakes and sauces.',
   array['Rich molasses flavour', 'Keeps soft', '500g pack'],
   '[]'::jsonb),
  ('fine-sea-salt-750g', 'Fine Sea Salt, 750g', 'Saltworks', 'groceries', 1.49, 1.67, 4.8, 527, 20, 32, false, '{}',
   'Naturally evaporated sea salt with a clean flavour for cooking and the table.',
   array['Sun-evaporated', 'Fine grain', 'Recyclable tub'],
   '[]'::jsonb),
  ('whole-black-peppercorns-100g', 'Whole Black Peppercorns, 100g', 'Spice Route', 'groceries', 3.29, null, 4.4, 223, 99, 33, false, '{}',
   'Bold, fragrant peppercorns to grind fresh over any dish.',
   array['Sun-dried', 'Strong aroma', 'Grinder-friendly'],
   '[]'::jsonb),
  ('smoked-paprika-90g', 'Smoked Paprika, 90g', 'Spice Route', 'groceries', 2.99, null, 4.7, 117, 12, 34, false, '{}',
   'Sweet smoked paprika that adds depth to stews, roast vegetables and rubs.',
   array['Oak-smoked', 'Sweet variety', 'Airtight jar'],
   '[]'::jsonb),
  ('ground-turmeric-100g', 'Ground Turmeric, 100g', 'Spice Route', 'groceries', 2.49, null, 4.2, 72, 50, 35, false, '{}',
   'Vibrant golden turmeric for curries, rice and golden milk.',
   array['Bright colour', 'Earthy flavour', '100g jar'],
   '[]'::jsonb),
  ('curry-powder-medium-100g', 'Curry Powder, Medium, 100g', 'Spice Route', 'groceries', 2.69, null, 4.1, 1304, 88, 36, false, '{}',
   'A balanced medium-heat blend of coriander, cumin, turmeric and fenugreek.',
   array['Medium heat', 'Ready blend', '100g tin'],
   '[]'::jsonb),
  ('ground-cinnamon-80g', 'Ground Cinnamon, 80g', 'Spice Route', 'groceries', 2.79, 3.49, 4.8, 47, 22, 37, true, '{}',
   'Warm, sweet cinnamon for baking, porridge and hot drinks.',
   array['Fragrant', 'Fine ground', '80g jar'],
   '[]'::jsonb),
  ('tomato-passata-700g', 'Tomato Passata, 700g', 'Bella Terra', 'groceries', 1.99, null, 4.0, 462, 82, 38, false, '{}',
   'Smooth sieved tomatoes with no seeds or skin: the base for pasta sauces and soups.',
   array['Made with ripe tomatoes', 'No added sugar', 'Glass jar'],
   '[]'::jsonb),
  ('chopped-tomatoes-in-juice-400g-pack-of-6', 'Chopped Tomatoes in Juice, 400g (Pack of 6)', 'Bella Terra', 'groceries', 6.49, null, 4.5, 1746, 103, 39, false, '{}',
   'Ripe chopped tomatoes in juice for stews, curries and chilli.',
   array['Pack of 6', 'No preservatives', 'Easy-open cans'],
   '[]'::jsonb),
  ('tomato-paste-double-concentrate-200g', 'Tomato Paste, Double Concentrate, 200g', 'Bella Terra', 'groceries', 1.59, null, 4.5, 64, 20, 40, false, '{}',
   'Rich double-concentrated paste for deep-flavoured sauces.',
   array['Double concentrate', 'Squeeze tube', 'No additives'],
   '[]'::jsonb),
  ('baked-beans-in-tomato-sauce-415g-pack-of-4', 'Baked Beans in Tomato Sauce, 415g (Pack of 4)', 'Pantry Pride', 'groceries', 3.99, null, 4.1, 345, 41, 41, true, '{}',
   'Haricot beans in a classic tomato sauce. Ready in 2 minutes.',
   array['Pack of 4', 'Source of fibre', 'No artificial colours'],
   '[]'::jsonb),
  ('chickpeas-in-water-400g-pack-of-6', 'Chickpeas in Water, 400g (Pack of 6)', 'Pantry Pride', 'groceries', 5.49, 6.86, 4.0, 202, 28, 42, false, '{}',
   'Tender ready-cooked chickpeas for hummus, salads and curries.',
   array['Pack of 6', 'Ready to eat', 'High in protein'],
   '[]'::jsonb),
  ('red-kidney-beans-400g-pack-of-6', 'Red Kidney Beans, 400g (Pack of 6)', 'Pantry Pride', 'groceries', 5.29, null, 4.5, 39, 96, 43, false, '{}',
   'Plump, tender kidney beans for chilli, rice and salads.',
   array['Pack of 6', 'Cooked and ready', 'High in fibre'],
   '[]'::jsonb),
  ('sweetcorn-kernels-340g-pack-of-4', 'Sweetcorn Kernels, 340g (Pack of 4)', 'Pantry Pride', 'groceries', 3.69, null, 4.4, 14, 8, 44, false, '{}',
   'Sweet golden kernels that add colour to salads, pizza and fried rice.',
   array['Pack of 4', 'No added sugar', 'Ready to serve'],
   '[]'::jsonb),
  ('sardines-in-olive-oil-120g-pack-of-3', 'Sardines in Olive Oil, 120g (Pack of 3)', 'Coastal Catch', 'groceries', 4.89, null, 4.1, 32, 47, 45, false, '{}',
   'Whole sardines packed in olive oil: quick protein for toast or salads.',
   array['Rich in omega-3', 'Pack of 3', 'Easy-open lid'],
   '[]'::jsonb),
  ('tuna-chunks-in-sunflower-oil-160g-pack-of-4', 'Tuna Chunks in Sunflower Oil, 160g (Pack of 4)', 'Coastal Catch', 'groceries', 6.99, null, 4.0, 303, 119, 46, true, '{}',
   'Firm chunks of tuna, line caught and packed in sunflower oil.',
   array['Pack of 4', 'High in protein', 'Responsibly sourced'],
   '[]'::jsonb),
  ('peanut-butter-crunchy-340g', 'Peanut Butter, Crunchy, 340g', 'Nutty Lane', 'groceries', 3.29, 3.88, 4.1, 306, 33, 47, false, '{}',
   'Roasted peanuts ground with a touch of salt. Crunchy bits in every spoonful.',
   array['94% peanuts', 'No palm oil', 'Crunchy'],
   '[]'::jsonb),
  ('smooth-almond-butter-250g', 'Smooth Almond Butter, 250g', 'Nutty Lane', 'groceries', 6.49, null, 4.2, 1066, 112, 48, false, '{}',
   'Silky roasted almond butter to spread, stir into porridge or blend in smoothies.',
   array['100% almonds', 'No added sugar', 'Rich in vitamin E'],
   '[]'::jsonb),
  ('chocolate-hazelnut-spread-400g', 'Chocolate Hazelnut Spread, 400g', 'Nutty Lane', 'groceries', 3.99, null, 4.1, 319, 19, 49, false, '{}',
   'Creamy cocoa and hazelnut spread for pancakes, toast and bakes.',
   array['Made with hazelnuts', 'Smooth texture', 'Jar with easy-scoop lid'],
   '[]'::jsonb),
  ('strawberry-jam-340g', 'Strawberry Jam, 340g', 'Orchard & Vine', 'groceries', 2.49, 3.31, 4.4, 316, 35, 50, true, '{}',
   'Thick strawberry preserve with whole fruit pieces.',
   array['Made with 50% fruit', 'No artificial colours', 'Glass jar'],
   '[]'::jsonb),
  ('raw-wildflower-honey-500g', 'Raw Wildflower Honey, 500g', 'Hive & Co', 'groceries', 8.99, 10.61, 4.3, 1385, 3, 51, false, '{}',
   'Unpasteurised honey from wildflower meadows with a floral aroma.',
   array['Raw and unheated', 'Squeezable jar', 'Locally sourced'],
   '[]'::jsonb),
  ('maple-syrup-250ml', 'Maple Syrup, 250ml', 'Hive & Co', 'groceries', 7.49, null, 4.4, 1571, 45, 52, false, '{}',
   'Pure Grade A amber maple syrup for pancakes, waffles and baking.',
   array['100% pure', 'Grade A amber', 'Glass bottle'],
   '[]'::jsonb),
  ('green-tea-bags-box-of-80', 'Green Tea Bags, Box of 80', 'Leaf & Kettle', 'groceries', 3.99, null, 4.2, 97, 84, 53, false, '{}',
   'Light, refreshing green tea with a clean grassy finish.',
   array['80 bags', 'Plant-based bags', 'Rich in antioxidants'],
   '[]'::jsonb),
  ('english-breakfast-tea-160-bags', 'English Breakfast Tea, 160 Bags', 'Leaf & Kettle', 'groceries', 4.49, 5.3, 4.4, 24, 32, 54, false, '{}',
   'A robust black tea blend for a proper morning brew.',
   array['160 bags', 'Strong and malty', 'Ethically sourced'],
   '[]'::jsonb),
  ('chamomile-herbal-tea-box-of-20', 'Chamomile Herbal Tea, Box of 20', 'Leaf & Kettle', 'groceries', 2.79, null, 4.2, 1567, 96, 55, true, '{}',
   'Soothing caffeine-free chamomile flowers to unwind with in the evening.',
   array['Caffeine free', '20 bags', 'Whole flower heads'],
   '[]'::jsonb),
  ('instant-coffee-granules-200g', 'Instant Coffee Granules, 200g', 'Highland Roast', 'groceries', 5.99, null, 4.2, 343, 38, 56, false, '{}',
   'Smooth medium-roast granules that dissolve instantly.',
   array['Medium roast', 'Rich crema-like foam', 'Resealable jar'],
   '[]'::jsonb),
  ('drinking-chocolate-powder-500g', 'Drinking Chocolate Powder, 500g', 'Cocoa House', 'groceries', 4.29, 5.36, 4.4, 389, 47, 57, true, '{}',
   'Rich cocoa powder that mixes into hot or cold milk.',
   array['Real cocoa', 'Mixes easily', '500g tub'],
   '[]'::jsonb),
  ('full-cream-long-life-milk-1l-pack-of-6', 'Full Cream Long Life Milk, 1L (Pack of 6)', 'Dairy Dale', 'groceries', 6.99, null, 4.0, 142, 66, 58, false, '{}',
   'UHT full cream milk that keeps in your cupboard until opened.',
   array['Pack of 6', 'No refrigeration until opened', 'Source of calcium'],
   '[]'::jsonb),
  ('unsweetened-almond-milk-1l', 'Unsweetened Almond Milk, 1L', 'Green Sip', 'groceries', 2.29, 2.7, 4.4, 55, 17, 59, false, '{}',
   'Smooth plant milk low in calories, great with cereal and coffee.',
   array['Dairy free', 'Fortified with calcium', 'No added sugar'],
   '[]'::jsonb),
  ('salted-butter-250g', 'Salted Butter, 250g', 'Dairy Dale', 'groceries', 3.19, null, 4.7, 630, 25, 60, false, '{}',
   'Creamy salted butter churned from fresh cream.',
   array['Creamy', 'Foil wrapped', '250g block'],
   '[]'::jsonb),
  ('mature-cheddar-cheese-400g', 'Mature Cheddar Cheese, 400g', 'Dairy Dale', 'groceries', 5.49, null, 4.8, 87, 115, 61, false, '{}',
   'Aged mature cheddar with a full, tangy bite and crumbly texture.',
   array['Matured 9 months', 'Great for grating', '400g block'],
   '[]'::jsonb),
  ('free-range-eggs-tray-of-12', 'Free-Range Eggs, Tray of 12', 'FreshFarm', 'groceries', 3.99, null, 4.1, 1571, 46, 62, false, '{}',
   'Large free-range eggs with deep golden yolks.',
   array['Free range', 'Grade A large', 'Tray of 12'],
   '[]'::jsonb),
  ('sourdough-loaf-800g', 'Sourdough Loaf, 800g', 'Crust & Crumb', 'groceries', 4.29, null, 4.3, 12, 70, 63, false, '{}',
   'Slow-fermented sourdough with a crackly crust and chewy crumb.',
   array['48-hour ferment', 'No additives', 'Baked daily'],
   '[]'::jsonb),
  ('sea-salt-potato-crisps-150g', 'Sea Salt Potato Crisps, 150g', 'Crunchtime', 'groceries', 1.99, null, 4.8, 36, 47, 64, false, '{}',
   'Thick-cut kettle crisps seasoned only with sea salt.',
   array['Kettle cooked', 'No artificial flavours', '150g bag'],
   '[]'::jsonb),
  ('mixed-nuts-roasted-and-salted-400g', 'Mixed Nuts, Roasted and Salted, 400g', 'Nutty Lane', 'groceries', 6.99, null, 4.2, 1018, 80, 65, false, '{}',
   'A hearty mix of almonds, cashews, hazelnuts and peanuts.',
   array['Dry roasted', 'Rich in protein', 'Resealable pouch'],
   '[]'::jsonb),
  ('dark-chocolate-70-cocoa-bar-100g', 'Dark Chocolate 70% Cocoa Bar, 100g', 'Cocoa House', 'groceries', 2.49, 3.11, 4.1, 422, 105, 66, false, '{}',
   'Intense dark chocolate with fruity notes and a clean snap.',
   array['70% cocoa', 'Ethically sourced cocoa', 'Vegan friendly'],
   '[]'::jsonb),
  ('sparkling-mineral-water-1-5l-pack-of-6', 'Sparkling Mineral Water, 1.5L (Pack of 6)', 'Clearspring', 'groceries', 5.49, null, 4.9, 22, 102, 67, false, '{}',
   'Naturally carbonated mineral water, crisp and refreshing.',
   array['Pack of 6', 'Naturally sparkling', 'Recyclable bottles'],
   '[]'::jsonb),
  ('100-orange-juice-1l', '100% Orange Juice, 1L', 'Orchard & Vine', 'groceries', 2.99, null, 4.7, 33, 54, 68, false, '{}',
   'Pressed from ripe oranges with no added sugar.',
   array['Not from concentrate', 'No added sugar', '1L carton'],
   '[]'::jsonb),
  ('pro-55-4k-smart-tv', 'Pro 55" 4K Smart TV', 'Visiora', 'electronics', 429, null, 4.0, 833, 63, 69, false, '{}',
   '55-inch 4K UHD LED display with built-in streaming apps, HDR10 and voice remote.',
   array['4K UHD HDR10', 'Built-in streaming apps', '3 HDMI ports'],
   '[]'::jsonb),
  ('essential-43-full-hd-smart-tv', 'Essential 43" Full HD Smart TV', 'Visiora', 'electronics', 259, null, 4.1, 1460, 82, 70, false, '{}',
   'A compact 43-inch Full HD smart TV that fits bedrooms and small living rooms.',
   array['Full HD 1080p', 'Wi-Fi smart platform', 'Wall-mount ready'],
   '[]'::jsonb),
  ('ultra-65-qled-4k-tv', 'Ultra 65" QLED 4K TV', 'Visiora', 'electronics', 789, null, 4.1, 370, 68, 71, false, '{}',
   'Quantum-dot colour, 120Hz refresh rate and low-latency game mode on a 65-inch panel.',
   array['QLED colour', '120Hz panel', 'Game mode'],
   '[]'::jsonb),
  ('dolby-soundbar-with-wireless-subwoofer', 'Dolby Soundbar with Wireless Subwoofer', 'AeroSound', 'electronics', 149, null, 4.7, 397, 93, 72, false, '{}',
   '2.1-channel soundbar with a wireless subwoofer for cinema-style bass.',
   array['2.1 channels', 'HDMI ARC', 'Bluetooth streaming'],
   '[]'::jsonb),
  ('compact-home-theatre-5-1-system', 'Compact Home Theatre 5.1 System', 'AeroSound', 'electronics', 219, 258.99, 4.6, 36, 6, 73, false, '{}',
   'Five satellite speakers and a powered subwoofer for immersive movie nights.',
   array['5.1 surround', '500W peak power', 'HDMI and optical input'],
   '[]'::jsonb),
  ('true-wireless-earbuds', 'True Wireless Earbuds', 'AeroSound', 'electronics', 39.99, null, 4.4, 598, 75, 74, false, '{}',
   'Comfortable in-ear buds with clear calls, touch controls and a pocket charging case.',
   array['24-hour total battery', 'Touch controls', 'IPX4 sweat resistant'],
   '[{"name": "Colour", "options": [{"label": "Black"}, {"label": "White"}]}]'::jsonb),
  ('noise-cancelling-earbuds-pro', 'Noise-Cancelling Earbuds Pro', 'AeroSound', 'electronics', 79.99, 89.99, 4.8, 21, 101, 75, false, '{}',
   'Hybrid active noise cancelling in a tiny earbud, with a transparency mode.',
   array['Hybrid ANC', 'Transparency mode', 'Wireless charging case'],
   '[{"name": "Colour", "options": [{"label": "Black"}, {"label": "White"}]}]'::jsonb),
  ('wired-studio-headphones', 'Wired Studio Headphones', 'Kova', 'electronics', 64.99, 76.99, 4.8, 293, 83, 76, false, '{}',
   'Closed-back monitor headphones with a flat, accurate response for mixing and listening.',
   array['40mm drivers', 'Detachable cable', 'Folding design'],
   '[{"name": "Colour", "options": [{"label": "Black"}, {"label": "White"}]}]'::jsonb),
  ('gaming-headset-with-boom-mic', 'Gaming Headset with Boom Mic', 'Kova', 'electronics', 49.99, null, 4.8, 1073, 32, 77, false, '{}',
   'Surround-sound gaming headset with a flip-to-mute microphone and memory-foam pads.',
   array['Virtual 7.1 sound', 'Flip-to-mute mic', 'Works with PC and consoles'],
   '[]'::jsonb),
  ('usb-condenser-microphone', 'USB Condenser Microphone', 'Kova', 'electronics', 54.99, null, 4.2, 767, 42, 78, false, '{}',
   'Plug-and-play cardioid microphone for streaming, podcasts and calls.',
   array['Cardioid pattern', 'Zero-latency monitoring', 'Desk stand included'],
   '[]'::jsonb),
  ('mechanical-gaming-keyboard', 'Mechanical Gaming Keyboard', 'Kova', 'electronics', 59.99, 74.99, 4.1, 50, 41, 79, false, '{}',
   'Hot-swappable mechanical keyboard with per-key RGB and a detachable USB-C cable.',
   array['Hot-swappable switches', 'RGB backlight', 'Full-size layout'],
   '[{"name": "Colour", "options": [{"label": "Black"}, {"label": "White"}]}]'::jsonb),
  ('compact-wireless-keyboard', 'Compact Wireless Keyboard', 'Kova', 'electronics', 29.99, 35.99, 4.0, 229, 38, 80, false, '{}',
   'Slim quiet keyboard that connects to three devices over Bluetooth.',
   array['Multi-device pairing', '3-month battery', 'Low-profile keys'],
   '[{"name": "Colour", "options": [{"label": "Black"}, {"label": "White"}]}]'::jsonb),
  ('ergonomic-wireless-mouse', 'Ergonomic Wireless Mouse', 'Kova', 'electronics', 24.99, null, 4.7, 354, 5, 81, false, '{}',
   'Sculpted right-handed mouse with silent clicks and a 12-month battery.',
   array['Silent clicks', 'Adjustable DPI', 'Bluetooth and USB receiver'],
   '[{"name": "Colour", "options": [{"label": "Black"}, {"label": "White"}]}]'::jsonb),
  ('gaming-mouse-16000-dpi', 'Gaming Mouse, 16000 DPI', 'Kova', 'electronics', 34.99, null, 4.8, 1730, 89, 82, false, '{}',
   'Lightweight wired gaming mouse with a precise optical sensor and 6 programmable buttons.',
   array['16000 DPI sensor', '6 programmable buttons', 'Braided cable'],
   '[{"name": "Colour", "options": [{"label": "Black"}, {"label": "White"}]}]'::jsonb),
  ('xl-desk-mat-900mm', 'XL Desk Mat, 900mm', 'Kova', 'electronics', 17.99, null, 4.2, 74, 114, 83, false, '{}',
   'Smooth stitched-edge mat that fits keyboard and mouse.',
   array['900 x 400mm', 'Non-slip base', 'Water resistant'],
   '[]'::jsonb),
  ('27-qhd-ips-monitor', '27" QHD IPS Monitor', 'Pixelon', 'electronics', 229, 304.99, 4.8, 333, 96, 84, true, '{}',
   'Sharp 2560 x 1440 IPS monitor with slim bezels and a height-adjustable stand.',
   array['QHD 1440p', '75Hz IPS', 'HDMI and DisplayPort'],
   '[]'::jsonb),
  ('24-full-hd-monitor', '24" Full HD Monitor', 'Pixelon', 'electronics', 119, null, 4.0, 153, 39, 85, false, '{}',
   'Everyday 24-inch monitor with eye-care flicker-free technology.',
   array['Full HD', 'Flicker free', 'VESA mountable'],
   '[]'::jsonb),
  ('34-ultrawide-curved-monitor', '34" Ultrawide Curved Monitor', 'Pixelon', 'electronics', 379, null, 4.8, 43, 107, 86, false, '{}',
   'Immersive 21:9 curved display for multitasking and games.',
   array['3440 x 1440', '144Hz', 'Curved VA panel'],
   '[]'::jsonb),
  ('1080p-webcam-with-privacy-shutter', '1080p Webcam with Privacy Shutter', 'Pixelon', 'electronics', 39.99, null, 4.2, 16, 37, 87, false, '{}',
   'Full HD webcam with autofocus, stereo mics and a privacy cover.',
   array['1080p at 30fps', 'Dual microphones', 'Privacy shutter'],
   '[]'::jsonb),
  ('portable-ssd-1tb', 'Portable SSD, 1TB', 'Vaultly', 'electronics', 99.99, null, 4.1, 68, 44, 88, false, '{}',
   'Pocket-size USB-C SSD with read speeds up to 1050MB/s.',
   array['1TB capacity', '1050MB/s reads', 'Shock resistant'],
   '[]'::jsonb),
  ('portable-hard-drive-2tb', 'Portable Hard Drive, 2TB', 'Vaultly', 'electronics', 74.99, 83.99, 4.7, 421, 5, 89, false, '{}',
   'Reliable USB 3.0 external drive for backups and media libraries.',
   array['2TB capacity', 'USB 3.0', 'Plug and play'],
   '[]'::jsonb),
  ('usb-flash-drive-128gb', 'USB Flash Drive, 128GB', 'Vaultly', 'electronics', 12.99, null, 4.3, 1412, 43, 90, true, '{}',
   'A compact metal USB 3.2 drive for everyday transfers.',
   array['128GB', 'USB 3.2', 'Keyring loop'],
   '[]'::jsonb),
  ('microsd-card-256gb', 'microSD Card, 256GB', 'Vaultly', 'electronics', 24.99, null, 4.8, 84, 66, 91, false, '{}',
   'High-speed card for phones, drones and action cameras.',
   array['256GB', 'A2/V30 rated', 'Adapter included'],
   '[]'::jsonb),
  ('wi-fi-6-router-ax3000', 'Wi-Fi 6 Router, AX3000', 'NetSphere', 'electronics', 89.99, 112.99, 3.9, 310, 93, 92, false, '{}',
   'Dual-band Wi-Fi 6 router covering up to 120 sqm with 4 gigabit ports.',
   array['AX3000 speeds', 'Covers 120 sqm', 'Parental controls'],
   '[]'::jsonb),
  ('mesh-wi-fi-system-2-pack', 'Mesh Wi-Fi System (2 pack)', 'NetSphere', 'electronics', 159, null, 4.1, 327, 80, 93, false, '{}',
   'Two nodes cover up to 300 sqm with seamless roaming.',
   array['Covers 300 sqm', 'Self-healing mesh', 'Easy app setup'],
   '[]'::jsonb),
  ('wi-fi-range-extender', 'Wi-Fi Range Extender', 'NetSphere', 'electronics', 29.99, null, 4.7, 83, 23, 94, false, '{}',
   'Plug-in repeater that pushes signal into dead spots.',
   array['Dual band', 'Ethernet port', 'Plug-in design'],
   '[]'::jsonb),
  ('8-port-gigabit-network-switch', '8-Port Gigabit Network Switch', 'NetSphere', 'electronics', 22.99, null, 4.7, 372, 75, 95, false, '{}',
   'Plug-and-play unmanaged switch for home offices and media centres.',
   array['8 gigabit ports', 'Fanless', 'Metal case'],
   '[]'::jsonb),
  ('cat6-ethernet-cable-10m', 'Cat6 Ethernet Cable, 10m', 'NetSphere', 'electronics', 8.99, 10.61, 4.3, 772, 47, 96, false, '{}',
   'Flat, tangle-free Cat6 cable for wired speeds up to 1Gbps.',
   array['10m length', 'Gold-plated plugs', 'Flat design'],
   '[]'::jsonb),
  ('streaming-media-stick-4k', 'Streaming Media Stick 4K', 'Streamly', 'electronics', 39.99, null, 4.1, 1200, 100, 97, false, '{}',
   'Turns any HDMI TV into a smart TV with 4K HDR streaming.',
   array['4K HDR', 'Voice remote', 'Wi-Fi 6'],
   '[]'::jsonb),
  ('smart-plug-2-pack', 'Smart Plug (2 pack)', 'Streamly', 'electronics', 17.99, null, 4.3, 10, 43, 98, false, '{}',
   'Control lamps and appliances from your phone or with voice commands.',
   array['Schedules and timers', 'Works with voice assistants', '2 pack'],
   '[]'::jsonb),
  ('smart-led-bulb-colour-4-pack', 'Smart LED Bulb, Colour (4 pack)', 'Streamly', 'electronics', 29.99, null, 4.4, 1071, 57, 99, false, '{}',
   'Wi-Fi bulbs with 16 million colours and adjustable white light.',
   array['16 million colours', 'E27 fitting', '4 pack'],
   '[]'::jsonb),
  ('video-doorbell-1080p', 'Video Doorbell, 1080p', 'Streamly', 'electronics', 79.99, 99.99, 4.1, 444, 109, 100, false, '{}',
   'See and speak to visitors from your phone with motion alerts.',
   array['1080p HD', 'Two-way audio', 'Night vision'],
   '[]'::jsonb),
  ('indoor-security-camera-360', 'Indoor Security Camera, 360°', 'Streamly', 'electronics', 34.99, 46.99, 4.2, 328, 118, 101, false, '{}',
   'Pan and tilt camera with motion tracking and local storage.',
   array['360° pan/tilt', 'Motion tracking', 'microSD slot'],
   '[]'::jsonb),
  ('outdoor-security-camera', 'Outdoor Security Camera', 'Streamly', 'electronics', 69.99, 82.99, 4.2, 76, 82, 102, false, '{}',
   'Weatherproof camera with colour night vision and a built-in siren.',
   array['IP66 weatherproof', 'Colour night vision', 'Built-in siren'],
   '[]'::jsonb),
  ('mirrorless-camera-kit-with-16-50mm-lens', 'Mirrorless Camera Kit with 16-50mm Lens', 'Snapix', 'electronics', 549, null, 4.5, 225, 73, 103, false, '{}',
   '24MP mirrorless camera with a versatile kit lens and 4K video.',
   array['24MP sensor', '4K video', 'Tilting touchscreen'],
   '[]'::jsonb),
  ('action-camera-4k-waterproof', 'Action Camera 4K Waterproof', 'Snapix', 'electronics', 89.99, 100.99, 4.2, 118, 85, 104, false, '{}',
   'Rugged 4K action camera waterproof to 10m with mounting accessories.',
   array['4K at 60fps', 'Waterproof to 10m', 'Image stabilisation'],
   '[]'::jsonb),
  ('lightweight-camera-tripod', 'Lightweight Camera Tripod', 'Snapix', 'electronics', 26.99, 31.99, 4.7, 46, 65, 105, false, '{}',
   'Aluminium tripod with a quick-release plate that extends to 160cm.',
   array['Extends to 160cm', 'Quick-release plate', 'Carry bag'],
   '[]'::jsonb),
  ('portable-ring-light-with-stand', 'Portable Ring Light with Stand', 'Snapix', 'electronics', 21.99, null, 4.1, 254, 87, 106, false, '{}',
   '10-inch LED ring light with a phone holder and three colour modes.',
   array['3 colour modes', 'Adjustable brightness', 'Phone holder'],
   '[]'::jsonb),
  ('wireless-charging-pad-15w', 'Wireless Charging Pad, 15W', 'Voltix', 'electronics', 19.99, null, 4.5, 86, 45, 107, false, '{}',
   'Fast Qi wireless charger with a non-slip surface.',
   array['15W fast charge', 'LED indicator', 'Case friendly'],
   '[]'::jsonb),
  ('65w-gan-wall-charger', '65W GaN Wall Charger', 'Voltix', 'electronics', 32.99, 38.99, 4.5, 61, 72, 108, false, '{}',
   'Compact 3-port GaN charger powers a laptop and two phones at once.',
   array['65W output', '2 USB-C and 1 USB-A', 'Foldable plug'],
   '[]'::jsonb),
  ('power-bank-20000mah', 'Power Bank, 20000mAh', 'Voltix', 'electronics', 34.99, 43.99, 4.6, 66, 112, 109, false, '{}',
   'High-capacity power bank with fast charging and a digital display.',
   array['20000mAh', '22.5W fast charge', 'LED display'],
   '[]'::jsonb),
  ('6-way-surge-protected-extension-lead-3m', '6-Way Surge Protected Extension Lead, 3m', 'Voltix', 'electronics', 16.99, null, 4.7, 435, 31, 110, false, '{}',
   'Six sockets and two USB ports with built-in surge protection.',
   array['6 sockets + 2 USB', '3m cable', 'Surge protection'],
   '[]'::jsonb),
  ('bluetooth-turntable-with-speakers', 'Bluetooth Turntable with Speakers', 'Retrowave', 'electronics', 119, null, 4.0, 1418, 48, 111, false, '{}',
   'Belt-drive record player with built-in speakers and Bluetooth output.',
   array['3 speeds', 'Bluetooth out', 'RCA output'],
   '[]'::jsonb),
  ('portable-cd-player-with-speakers', 'Portable CD Player with Speakers', 'Retrowave', 'electronics', 44.99, null, 4.2, 1224, 22, 112, false, '{}',
   'Play discs anywhere with FM radio and headphone jack.',
   array['Anti-skip', 'FM radio', 'Battery or mains'],
   '[]'::jsonb),
  ('digital-dab-radio', 'Digital DAB+ Radio', 'Retrowave', 'electronics', 39.99, null, 4.6, 85, 98, 113, false, '{}',
   'Compact radio with DAB+/FM, alarm and a clear display.',
   array['DAB+/FM', 'Dual alarm', 'Headphone jack'],
   '[]'::jsonb),
  ('gaming-controller-wireless', 'Gaming Controller, Wireless', 'Playfield', 'electronics', 44.99, null, 4.9, 42, 95, 114, false, '{}',
   'Ergonomic controller with textured grips and up to 30 hours of battery.',
   array['30-hour battery', 'Programmable back buttons', 'PC and Android'],
   '[]'::jsonb),
  ('handheld-retro-game-console', 'Handheld Retro Game Console', 'Playfield', 'electronics', 59.99, 79.99, 4.5, 106, 53, 115, false, '{}',
   '3.5-inch display with 500 built-in classic-style games.',
   array['500 games', '3.5" display', 'Rechargeable'],
   '[]'::jsonb),
  ('laser-projector-mini-hd', 'Laser Projector, Mini HD', 'Visiora', 'electronics', 139, null, 4.2, 207, 82, 116, true, '{}',
   'Pocket-size projector with a 100-inch image and built-in speaker.',
   array['Up to 100" picture', 'HDMI and USB', 'Built-in speaker'],
   '[]'::jsonb),
  ('universal-laptop-stand-aluminium', 'Universal Laptop Stand, Aluminium', 'Kova', 'electronics', 27.99, 34.99, 4.2, 202, 71, 117, false, '{}',
   'Foldable stand that lifts your laptop to eye level for better posture.',
   array['6 height levels', 'Fits 10–17" laptops', 'Folds flat'],
   '[]'::jsonb),
  ('laptop-docking-station-9-in-1', 'Laptop Docking Station, 9-in-1', 'Kova', 'electronics', 54.99, 68.99, 4.5, 71, 82, 118, false, '{}',
   'USB-C hub adding HDMI, Ethernet, SD card, USB-A and 100W pass-through.',
   array['HDMI 4K', 'Gigabit Ethernet', '100W pass-through'],
   '[]'::jsonb),
  ('nova-lite-smartphone', 'Nova Lite Smartphone', 'Nova', 'gadgets', 149, 198.99, 4.0, 690, 82, 119, true, '{}',
   '6.6-inch display, 13MP camera and a 5000mAh battery for essentials on a budget.',
   array['6.6" HD+ screen', '5000mAh battery', 'Dual SIM'],
   '[{"name": "Storage", "options": [{"label": "128GB"}, {"label": "256GB", "delta": 50}]}, {"name": "Colour", "options": [{"label": "Graphite"}, {"label": "Silver"}]}]'::jsonb),
  ('nova-pro-smartphone', 'Nova Pro Smartphone', 'Nova', 'gadgets', 449, null, 4.1, 440, 75, 120, false, '{}',
   'AMOLED display, 108MP camera and 67W fast charging.',
   array['6.7" AMOLED 120Hz', '108MP camera', '67W fast charging'],
   '[{"name": "Storage", "options": [{"label": "128GB"}, {"label": "256GB", "delta": 50}]}, {"name": "Colour", "options": [{"label": "Graphite"}, {"label": "Silver"}]}]'::jsonb),
  ('nova-ultra-smartphone', 'Nova Ultra Smartphone', 'Nova', 'gadgets', 799, 998.99, 4.3, 301, 61, 121, false, '{}',
   'Flagship performance with a triple camera and a titanium frame.',
   array['Triple camera', 'Titanium frame', '5G ready'],
   '[{"name": "Storage", "options": [{"label": "128GB"}, {"label": "256GB", "delta": 50}]}, {"name": "Colour", "options": [{"label": "Graphite"}, {"label": "Silver"}]}]'::jsonb),
  ('nova-fold-flip-phone', 'Nova Fold Flip Phone', 'Nova', 'gadgets', 699, null, 4.6, 95, 112, 122, false, '{}',
   'A pocketable flip phone with a 6.7-inch folding display.',
   array['Folding AMOLED', 'Cover screen', '5G'],
   '[]'::jsonb),
  ('spark-go-smartphone', 'Spark Go Smartphone', 'Spark', 'gadgets', 99, null, 4.2, 1387, 31, 123, false, '{}',
   'A dependable entry phone with a big battery and clean software.',
   array['6.5" display', '4000mAh', 'Expandable storage'],
   '[{"name": "Storage", "options": [{"label": "128GB"}, {"label": "256GB", "delta": 50}]}, {"name": "Colour", "options": [{"label": "Graphite"}, {"label": "Silver"}]}]'::jsonb),
  ('spark-max-smartphone', 'Spark Max Smartphone', 'Spark', 'gadgets', 259, null, 4.2, 253, 101, 124, false, '{}',
   'Smooth 90Hz display, 64MP camera and 33W charging.',
   array['90Hz screen', '64MP camera', '33W charging'],
   '[{"name": "Storage", "options": [{"label": "128GB"}, {"label": "256GB", "delta": 50}]}, {"name": "Colour", "options": [{"label": "Graphite"}, {"label": "Silver"}]}]'::jsonb),
  ('rugged-outdoor-smartphone', 'Rugged Outdoor Smartphone', 'Bolt', 'gadgets', 329, null, 4.8, 851, 115, 125, false, '{}',
   'Military-grade drop protection with a 10000mAh battery.',
   array['IP68/IP69K', '10000mAh', 'Night vision camera'],
   '[]'::jsonb),
  ('basic-feature-phone', 'Basic Feature Phone', 'Bolt', 'gadgets', 24.99, null, 4.7, 27, 87, 126, false, '{}',
   'Simple, tough phone with month-long standby and a torch.',
   array['Dual SIM', 'FM radio', 'Long battery life'],
   '[]'::jsonb),
  ('pulsefit-band-2', 'PulseFit Band 2', 'PulseFit', 'gadgets', 34.99, 46.99, 4.0, 66, 95, 127, false, '{}',
   'Slim fitness band with heart-rate, SpO2 and 14-day battery.',
   array['14-day battery', 'SpO2 monitor', 'Water resistant 5ATM'],
   '[]'::jsonb),
  ('pulsefit-watch-pro-gps', 'PulseFit Watch Pro GPS', 'PulseFit', 'gadgets', 179, 223.99, 4.2, 392, 80, 128, false, '{}',
   'Built-in GPS, AMOLED display and 100+ sports modes.',
   array['Built-in GPS', 'AMOLED display', '100+ sports modes'],
   '[]'::jsonb),
  ('kids-gps-smartwatch', 'Kids GPS Smartwatch', 'PulseFit', 'gadgets', 59.99, null, 4.6, 273, 8, 129, false, '{}',
   'Calls, location tracking and a safe-zone alert for parents.',
   array['GPS tracking', 'Two-way calling', 'Parent app'],
   '[]'::jsonb),
  ('tablet-10-4-64gb', 'Tablet 10.4", 64GB', 'Slate', 'gadgets', 199, 234.99, 4.6, 1757, 24, 130, false, '{}',
   'Bright 10.4-inch tablet for reading, streaming and homework.',
   array['10.4" display', '64GB storage', 'Quad speakers'],
   '[]'::jsonb),
  ('tablet-pro-11-256gb', 'Tablet Pro 11", 256GB', 'Slate', 'gadgets', 449, null, 4.8, 226, 67, 131, false, '{}',
   'Fast 11-inch tablet with a 120Hz screen and stylus support.',
   array['120Hz display', '256GB storage', 'Stylus support'],
   '[]'::jsonb),
  ('kids-tablet-with-protective-case', 'Kids Tablet with Protective Case', 'Slate', 'gadgets', 89, null, 4.5, 31, 60, 132, false, '{}',
   'Durable tablet with parental controls and a bumper case.',
   array['Parental controls', 'Shockproof case', '2-year guarantee'],
   '[]'::jsonb),
  ('e-reader-6-glare-free', 'E-Reader, 6" Glare-Free', 'Pagelight', 'gadgets', 99, 116.99, 4.1, 190, 114, 133, false, '{}',
   'Paper-like display with adjustable warm light and weeks of battery.',
   array['300 ppi', 'Adjustable warm light', '8GB storage'],
   '[]'::jsonb),
  ('stylus-pen-for-tablets', 'Stylus Pen for Tablets', 'Slate', 'gadgets', 29.99, 35.99, 4.0, 812, 100, 134, false, '{}',
   'Pressure-sensitive stylus with palm rejection.',
   array['4096 pressure levels', 'Palm rejection', 'Magnetic attach'],
   '[]'::jsonb),
  ('phone-gimbal-stabiliser', 'Phone Gimbal Stabiliser', 'Snapix', 'gadgets', 79.99, null, 4.1, 57, 57, 135, false, '{}',
   '3-axis stabiliser for smooth handheld video.',
   array['3-axis', 'Object tracking', 'Foldable'],
   '[]'::jsonb),
  ('bluetooth-item-tracker-4-pack', 'Bluetooth Item Tracker (4 pack)', 'Locato', 'gadgets', 29.99, null, 4.2, 216, 111, 136, false, '{}',
   'Find keys, bags and wallets on a map, with a loud ringer.',
   array['1-year battery', 'Loud ringer', 'Works on both iOS and Android'],
   '[]'::jsonb),
  ('smart-ring-sleep-tracker', 'Smart Ring Sleep Tracker', 'PulseFit', 'gadgets', 129, 171.99, 4.7, 177, 36, 137, false, '{}',
   'A titanium ring tracking sleep, HRV and recovery.',
   array['Titanium', '7-day battery', 'Sleep score'],
   '[]'::jsonb),
  ('mini-bluetooth-selfie-remote', 'Mini Bluetooth Selfie Remote', 'Snapix', 'gadgets', 6.99, null, 4.6, 398, 51, 138, false, '{}',
   'Tiny wireless shutter for group photos and video.',
   array['10m range', 'Keychain size', 'Works with any phone'],
   '[]'::jsonb),
  ('phone-tripod-with-bluetooth-remote', 'Phone Tripod with Bluetooth Remote', 'Snapix', 'gadgets', 18.99, 23.74, 4.6, 869, 37, 139, false, '{}',
   'Flexible tripod with a phone clamp for vlogs and video calls.',
   array['Adjustable height', '360° ball head', 'Remote included'],
   '[]'::jsonb),
  ('clip-on-phone-lens-kit', 'Clip-On Phone Lens Kit', 'Snapix', 'gadgets', 16.99, null, 4.9, 75, 117, 140, false, '{}',
   'Wide-angle and macro lenses that clip on to any phone.',
   array['Wide and macro', 'Universal clip', 'Carry pouch'],
   '[]'::jsonb),
  ('magnetic-car-phone-mount', 'Magnetic Car Phone Mount', 'Voltix', 'gadgets', 13.99, null, 4.2, 51, 40, 141, false, '{}',
   'Strong magnetic mount for dashboard or air vent.',
   array['360° rotation', 'Fits all phones', 'One-hand use'],
   '[]'::jsonb),
  ('wireless-car-charger-mount', 'Wireless Car Charger Mount', 'Voltix', 'gadgets', 34.99, null, 4.9, 247, 7, 142, false, '{}',
   'Auto-clamping 15W wireless charger mount.',
   array['15W charging', 'Auto-clamp', 'Vent and dash mounts'],
   '[]'::jsonb),
  ('car-bluetooth-fm-transmitter', 'Car Bluetooth FM Transmitter', 'Voltix', 'gadgets', 14.99, null, 4.6, 980, 25, 143, false, '{}',
   'Play music and take calls through your car stereo.',
   array['Bluetooth 5.0', 'Dual USB ports', 'Hands-free calls'],
   '[]'::jsonb),
  ('dash-cam-1440p-with-night-vision', 'Dash Cam 1440p with Night Vision', 'Voltix', 'gadgets', 59.99, null, 4.5, 79, 93, 144, false, '{}',
   'Loop-recording dash cam with a wide-angle lens and G-sensor.',
   array['1440p recording', 'Night vision', 'G-sensor lock'],
   '[]'::jsonb),
  ('tyre-inflator-cordless', 'Tyre Inflator, Cordless', 'Voltix', 'gadgets', 39.99, null, 4.2, 60, 50, 145, false, '{}',
   'Digital inflator with an auto-stop pressure preset.',
   array['Auto stop', 'Digital gauge', 'LED light'],
   '[]'::jsonb),
  ('usb-c-to-usb-c-cable-2m-2-pack', 'USB-C to USB-C Cable, 2m (2 pack)', 'Voltix', 'gadgets', 11.99, 14.15, 4.8, 258, 107, 146, false, '{}',
   'Braided 100W cables with fast-charge and data support.',
   array['100W', 'Braided', '2 pack'],
   '[]'::jsonb),
  ('lightning-to-usb-c-cable-1m', 'Lightning to USB-C Cable, 1m', 'Voltix', 'gadgets', 12.99, null, 4.5, 27, 90, 147, false, '{}',
   'Certified fast-charging cable for older iPhone models.',
   array['Certified', 'Fast charging', 'Reinforced ends'],
   '[]'::jsonb),
  ('multi-device-charging-station', 'Multi-Device Charging Station', 'Voltix', 'gadgets', 44.99, null, 3.9, 171, 58, 148, true, '{}',
   'Six-port desktop charging dock for phones, tablets and watches.',
   array['6 ports', '60W total', 'Compact'],
   '[]'::jsonb),
  ('solar-power-bank-25000mah', 'Solar Power Bank, 25000mAh', 'Voltix', 'gadgets', 39.99, null, 4.4, 243, 27, 149, false, '{}',
   'Rugged power bank with a solar panel and torch for outdoor trips.',
   array['25000mAh', 'Solar trickle charge', 'Built-in torch'],
   '[]'::jsonb),
  ('phone-cooling-fan-clip-on', 'Phone Cooling Fan, Clip-On', 'Playfield', 'gadgets', 22.99, null, 4.0, 1509, 18, 150, false, '{}',
   'Magnetic semiconductor cooler for long gaming sessions.',
   array['Semiconductor cooling', 'RGB light', 'Quiet'],
   '[]'::jsonb),
  ('mobile-gaming-triggers', 'Mobile Gaming Triggers', 'Playfield', 'gadgets', 9.99, 11.79, 4.7, 1767, 39, 151, false, '{}',
   'Tactile shoulder triggers for shooters on your phone.',
   array['Fast response', 'Fits most phones', 'Pair'],
   '[]'::jsonb),
  ('smart-glasses-bluetooth-audio', 'Smart Glasses, Bluetooth Audio', 'Locato', 'gadgets', 99, 116.99, 4.7, 84, 81, 152, false, '{}',
   'Sunglass-style frames with open-ear speakers for music and calls.',
   array['Open-ear audio', 'Polarised lenses', 'IPX4'],
   '[]'::jsonb),
  ('pocket-translator-device', 'Pocket Translator Device', 'Locato', 'gadgets', 89, 99.99, 4.0, 181, 5, 153, true, '{}',
   'Two-way voice translator supporting 100+ languages.',
   array['100+ languages', 'Two-way voice', '4G and Wi-Fi'],
   '[]'::jsonb),
  ('portable-mini-printer', 'Portable Mini Printer', 'Snapix', 'gadgets', 54.99, null, 4.4, 303, 25, 154, false, '{}',
   'Print photos, labels and lists from your phone via Bluetooth.',
   array['Ink-free thermal', 'Bluetooth', 'Sticker paper'],
   '[]'::jsonb),
  ('digital-voice-recorder-16gb', 'Digital Voice Recorder, 16GB', 'Locato', 'gadgets', 42.99, 48.99, 4.6, 1138, 19, 155, false, '{}',
   'Voice-activated recorder for lectures and interviews.',
   array['16GB memory', 'Noise reduction', 'MP3 recording'],
   '[]'::jsonb),
  ('smart-scale-with-body-analysis', 'Smart Scale with Body Analysis', 'PulseFit', 'gadgets', 29.99, null, 4.3, 311, 3, 156, false, '{}',
   'Wi-Fi scale with 13 body metrics synced to your phone.',
   array['13 metrics', 'Wi-Fi and Bluetooth', 'Unlimited users'],
   '[]'::jsonb),
  ('smart-pen-digital-notebook', 'Smart Pen Digital Notebook', 'Pagelight', 'gadgets', 84.99, 100.99, 4.2, 1323, 88, 157, false, '{}',
   'Writes on real paper and saves digitally to your phone.',
   array['Handwriting to text', 'Cloud sync', '8GB storage'],
   '[]'::jsonb),
  ('portable-fan-rechargeable-handheld', 'Portable Fan, Rechargeable Handheld', 'Voltix', 'gadgets', 14.99, null, 4.5, 1540, 82, 158, false, '{}',
   'Pocket fan with three speeds and a 6-hour battery.',
   array['6-hour battery', '3 speeds', 'Foldable handle'],
   '[]'::jsonb),
  ('neck-fan-bladeless', 'Neck Fan, Bladeless', 'Voltix', 'gadgets', 24.99, 33.99, 4.8, 233, 24, 159, false, '{}',
   'Wearable neck fan for commuting and outdoor work.',
   array['Bladeless', '4000mAh', '3 speeds'],
   '[]'::jsonb),
  ('digital-luggage-scale', 'Digital Luggage Scale', 'Locato', 'gadgets', 8.99, null, 4.2, 27, 23, 160, false, '{}',
   'Avoid airline fees with an accurate hook scale to 50kg.',
   array['Up to 50kg', 'Backlit LCD', 'Auto off'],
   '[]'::jsonb),
  ('smart-bluetooth-padlock', 'Smart Bluetooth Padlock', 'Locato', 'gadgets', 34.99, null, 4.3, 322, 83, 161, false, '{}',
   'Fingerprint padlock for gym lockers and luggage.',
   array['Fingerprint unlock', 'IP65', 'Rechargeable'],
   '[]'::jsonb),
  ('wireless-presenter-with-laser', 'Wireless Presenter with Laser', 'Kova', 'gadgets', 17.99, 22.49, 4.8, 789, 25, 162, false, '{}',
   'Slide clicker with a red laser pointer and 30m range.',
   array['30m range', 'Plug-and-play', 'Laser pointer'],
   '[]'::jsonb),
  ('pocket-projector-screen-stand', 'Pocket Projector Screen Stand', 'Visiora', 'gadgets', 34.99, 46.99, 4.1, 239, 47, 163, false, '{}',
   'Tripod screen that folds for travel.',
   array['60-inch', 'Wrinkle-free', 'Carry bag'],
   '[]'::jsonb),
  ('vr-headset-for-smartphones', 'VR Headset for Smartphones', 'Playfield', 'gadgets', 29.99, null, 4.7, 1582, 89, 164, false, '{}',
   'Adjustable headset that turns your phone into a VR viewer.',
   array['Fits up to 6.7" phones', 'Adjustable lenses', 'Breathable padding'],
   '[]'::jsonb),
  ('drone-with-4k-camera-foldable', 'Drone with 4K Camera, Foldable', 'Skyloft', 'gadgets', 199, null, 4.2, 199, 56, 165, true, '{}',
   'Beginner-friendly foldable drone with a 4K camera and GPS return.',
   array['4K camera', '25 minutes flight', 'GPS return to home'],
   '[]'::jsonb),
  ('mini-drone-for-kids', 'Mini Drone for Kids', 'Skyloft', 'gadgets', 39.99, null, 4.5, 490, 15, 166, true, '{}',
   'Small, stable drone with headless mode and one-key takeoff.',
   array['Altitude hold', 'Headless mode', '2 batteries'],
   '[]'::jsonb),
  ('smart-keychain-torch-usb-c', 'Smart Keychain Torch, USB-C', 'Locato', 'gadgets', 7.99, null, 4.3, 234, 53, 167, false, '{}',
   'Ultra-bright rechargeable torch on a carabiner clip.',
   array['500 lumens', 'USB-C rechargeable', 'Aluminium'],
   '[]'::jsonb),
  ('non-stick-frying-pan-28cm', 'Non-Stick Frying Pan, 28cm', 'Kitchenly', 'home', 24.99, null, 4.0, 522, 3, 168, false, '{}',
   'Forged aluminium pan with a PFOA-free non-stick coating and a stay-cool handle.',
   array['PFOA free', 'Induction compatible', 'Oven safe to 200°C'],
   '[]'::jsonb),
  ('stainless-steel-saucepan-set-3-piece', 'Stainless Steel Saucepan Set (3 piece)', 'Kitchenly', 'home', 54.99, null, 4.4, 64, 26, 169, false, '{}',
   'Tri-ply saucepans with glass lids for even heat and easy pouring.',
   array['Tri-ply base', 'Glass lids', 'Dishwasher safe'],
   '[]'::jsonb),
  ('cast-iron-skillet-26cm', 'Cast Iron Skillet, 26cm', 'Kitchenly', 'home', 32.99, 43.99, 4.4, 83, 19, 170, true, '{}',
   'Pre-seasoned cast iron skillet for searing, baking and campfire cooking.',
   array['Pre-seasoned', 'Lifetime durable', 'Oven safe'],
   '[]'::jsonb),
  ('ceramic-casserole-dish-with-lid-4l', 'Ceramic Casserole Dish with Lid, 4L', 'Kitchenly', 'home', 44.99, null, 4.1, 190, 75, 171, false, '{}',
   'Enamelled cast iron casserole for slow braises and stews.',
   array['4L capacity', 'Even heat retention', 'Oven safe'],
   '[]'::jsonb),
  ('pressure-cooker-6l', 'Pressure Cooker, 6L', 'Kitchenly', 'home', 59.99, 79.99, 4.4, 1344, 21, 172, false, '{}',
   'Stainless steel pressure cooker that cuts cooking time by up to 70%.',
   array['6L capacity', 'Safety valves', 'Works on all hobs'],
   '[]'::jsonb),
  ('chef-s-knife-20cm', 'Chef''s Knife, 20cm', 'Sharp & Co', 'home', 29.99, null, 4.3, 841, 63, 173, false, '{}',
   'High-carbon stainless blade with a full-tang, comfortable handle.',
   array['High-carbon steel', 'Full tang', 'Lifetime sharpness guide'],
   '[]'::jsonb),
  ('knife-block-set-6-piece', 'Knife Block Set (6 piece)', 'Sharp & Co', 'home', 69.99, null, 4.0, 551, 100, 174, false, '{}',
   'Everyday knife set with a wooden block and honing steel.',
   array['6 pieces', 'Hardwood block', 'Dishwasher-safe blades'],
   '[]'::jsonb),
  ('bamboo-chopping-board-set-3-piece', 'Bamboo Chopping Board Set (3 piece)', 'Nest & Co', 'home', 18.99, 21.27, 4.1, 83, 51, 175, false, '{}',
   'Three sizes of sustainable bamboo boards with juice grooves.',
   array['3 sizes', 'Juice groove', 'Easy-care bamboo'],
   '[]'::jsonb),
  ('silicone-utensil-set-12-piece', 'Silicone Utensil Set (12 piece)', 'Kitchenly', 'home', 21.99, 25.99, 4.0, 1286, 111, 176, false, '{}',
   'Heat-resistant spatulas, spoons and tongs with wooden handles.',
   array['Heat resistant to 230°C', 'Non-scratch', '12 pieces'],
   '[]'::jsonb),
  ('glass-food-storage-containers-10-piece', 'Glass Food Storage Containers (10 piece)', 'Kitchenly', 'home', 26.99, null, 4.7, 26, 34, 177, false, '{}',
   'Airtight glass containers with snap lids for the fridge, oven and microwave.',
   array['Airtight lids', 'Microwave and oven safe', '10 pieces'],
   '[]'::jsonb),
  ('insulated-water-bottle-750ml', 'Insulated Water Bottle, 750ml', 'Nest & Co', 'home', 17.99, null, 4.6, 381, 109, 178, false, '{}',
   'Double-wall stainless bottle keeps drinks cold for 24 hours or hot for 12.',
   array['24h cold / 12h hot', 'Leak-proof lid', 'BPA free'],
   '[]'::jsonb),
  ('air-fryer-5l-digital', 'Air Fryer, 5L Digital', 'Kitchenly', 'home', 79.99, null, 4.8, 385, 92, 179, false, '{}',
   'Cook crispy food with little to no oil. Eight presets and a dishwasher-safe basket.',
   array['5L basket', '8 presets', 'Dishwasher-safe parts'],
   '[]'::jsonb),
  ('digital-air-fryer-oven-12l', 'Digital Air Fryer Oven, 12L', 'Kitchenly', 'home', 119, null, 4.4, 762, 7, 180, true, '{}',
   'Multifunction air fryer with rotisserie, dehydrator and three racks.',
   array['12L capacity', 'Rotisserie', 'Dehydrator mode'],
   '[]'::jsonb),
  ('microwave-oven-20l-digital', 'Microwave Oven, 20L Digital', 'Kitchenly', 'home', 89, null, 3.9, 357, 23, 181, false, '{}',
   'Compact 800W microwave with defrost and 8 auto-cook menus.',
   array['800W power', 'Child lock', 'Digital timer'],
   '[]'::jsonb),
  ('4-slice-toaster-stainless-steel', '4-Slice Toaster, Stainless Steel', 'Kitchenly', 'home', 44.99, null, 4.4, 1121, 53, 182, false, '{}',
   'Wide slots, six browning levels and a crumb tray.',
   array['Wide slots', '6 browning levels', 'Bagel and defrost'],
   '[]'::jsonb),
  ('personal-blender-with-2-bottles', 'Personal Blender with 2 Bottles', 'Kitchenly', 'home', 34.99, null, 4.9, 903, 94, 183, false, '{}',
   'Blend smoothies and sauces and take them with you.',
   array['600W motor', '2 travel bottles', 'Easy clean'],
   '[]'::jsonb),
  ('jug-blender-1-5l-glass', 'Jug Blender, 1.5L Glass', 'Kitchenly', 'home', 59.99, 79.99, 4.9, 75, 48, 184, false, '{}',
   'Powerful glass jug blender for smoothies, soups and ice.',
   array['1000W motor', 'Glass jug', 'Pulse and ice-crush'],
   '[]'::jsonb),
  ('hand-stick-blender-set', 'Hand Stick Blender Set', 'Kitchenly', 'home', 39.99, null, 4.6, 383, 3, 185, false, '{}',
   'Multi-attachment stick blender with whisk and chopper.',
   array['800W', 'Variable speed', 'Whisk and chopper'],
   '[]'::jsonb),
  ('stand-mixer-5l', 'Stand Mixer, 5L', 'Kitchenly', 'home', 189, null, 4.2, 85, 30, 186, false, '{}',
   'Tilt-head mixer with dough hook, whisk and beater.',
   array['5L bowl', '10 speeds', 'Splash guard'],
   '[]'::jsonb),
  ('slow-cooker-6-5l', 'Slow Cooker, 6.5L', 'Kitchenly', 'home', 42.99, null, 4.6, 1418, 51, 187, false, '{}',
   'Set it and forget it: three heat settings for tender stews.',
   array['6.5L capacity', '3 heat settings', 'Removable stoneware'],
   '[]'::jsonb),
  ('multi-cooker-8-in-1', 'Multi Cooker, 8-in-1', 'Kitchenly', 'home', 99, null, 4.2, 391, 77, 188, false, '{}',
   'Pressure cook, sauté, steam, slow cook and more in one appliance.',
   array['8 functions', '6L', 'Keep-warm mode'],
   '[]'::jsonb),
  ('rice-cooker-1-8l', 'Rice Cooker, 1.8L', 'Kitchenly', 'home', 39.99, null, 4.1, 234, 29, 189, false, '{}',
   'Fluffy rice every time with automatic keep-warm.',
   array['1.8L', 'Non-stick pot', 'Steamer tray'],
   '[]'::jsonb),
  ('espresso-machine-with-milk-frother', 'Espresso Machine with Milk Frother', 'Kitchenly', 'home', 139, 155.99, 4.4, 277, 110, 190, false, '{}',
   '15-bar pump espresso maker with a steam wand for lattes.',
   array['15-bar pump', 'Steam wand', '1.5L tank'],
   '[]'::jsonb),
  ('filter-coffee-maker-1-25l', 'Filter Coffee Maker, 1.25L', 'Kitchenly', 'home', 34.99, null, 4.1, 539, 64, 191, false, '{}',
   'Brew up to 10 cups with a reusable filter and warming plate.',
   array['10 cups', 'Reusable filter', 'Anti-drip'],
   '[]'::jsonb),
  ('french-press-1l', 'French Press, 1L', 'Nest & Co', 'home', 19.99, null, 4.9, 1740, 41, 192, false, '{}',
   'Borosilicate glass press with a stainless steel plunger.',
   array['1L', 'Double filter', 'Heat-resistant glass'],
   '[]'::jsonb),
  ('manual-coffee-grinder', 'Manual Coffee Grinder', 'Nest & Co', 'home', 27.99, null, 4.7, 953, 68, 193, false, '{}',
   'Ceramic burr hand grinder with adjustable coarseness.',
   array['Ceramic burrs', 'Adjustable grind', 'Portable'],
   '[]'::jsonb),
  ('bed-sheet-set-double-100-cotton', 'Bed Sheet Set, Double, 100% Cotton', 'Nest & Co', 'home', 39.99, 53.99, 4.4, 608, 44, 194, true, '{}',
   'Breathable 200 thread-count cotton sheets: fitted, flat and two pillowcases.',
   array['200 thread count', 'Soft cotton', 'Machine washable'],
   '[{"name": "Colour", "options": [{"label": "Grey"}, {"label": "White"}, {"label": "Sage"}]}]'::jsonb),
  ('duvet-set-king-brushed-microfibre', 'Duvet Set, King, Brushed Microfibre', 'Nest & Co', 'home', 44.99, null, 4.3, 324, 32, 195, false, '{}',
   'Cosy duvet cover set with matching pillowcases.',
   array['Brushed microfibre', 'Easy care', 'Button closure'],
   '[{"name": "Colour", "options": [{"label": "Grey"}, {"label": "White"}, {"label": "Sage"}]}]'::jsonb),
  ('memory-foam-pillow-2-pack', 'Memory Foam Pillow (2 pack)', 'Nest & Co', 'home', 34.99, null, 4.0, 106, 15, 196, false, '{}',
   'Contouring pillows with a cooling gel layer and breathable cover.',
   array['Cooling gel', 'Removable cover', '2 pack'],
   '[]'::jsonb),
  ('all-season-duvet-10-5-tog-king', 'All-Season Duvet, 10.5 Tog, King', 'Nest & Co', 'home', 49.99, null, 4.3, 57, 3, 197, false, '{}',
   'Hollow-fibre duvet that''s warm in winter and light in summer.',
   array['10.5 tog', 'Hypoallergenic', 'Machine washable'],
   '[]'::jsonb),
  ('weighted-blanket-7kg', 'Weighted Blanket, 7kg', 'Nest & Co', 'home', 64.99, null, 4.7, 79, 29, 198, false, '{}',
   'Glass-bead weighted blanket that helps you feel calm and sleep deeper.',
   array['7kg', 'Breathable cotton', 'Even bead pockets'],
   '[{"name": "Colour", "options": [{"label": "Grey"}, {"label": "White"}, {"label": "Sage"}]}]'::jsonb),
  ('fleece-throw-blanket-150-x-200cm', 'Fleece Throw Blanket, 150 x 200cm', 'Nest & Co', 'home', 16.99, null, 4.5, 18, 82, 199, false, '{}',
   'Soft, warm fleece throw for sofas and beds.',
   array['150 x 200cm', 'Fade resistant', 'Machine washable'],
   '[{"name": "Colour", "options": [{"label": "Grey"}, {"label": "White"}, {"label": "Sage"}]}]'::jsonb),
  ('bath-towel-set-6-piece', 'Bath Towel Set (6 piece)', 'Nest & Co', 'home', 34.99, null, 4.3, 44, 6, 200, false, '{}',
   'Absorbent combed-cotton towels: 2 bath, 2 hand and 2 face.',
   array['550 GSM', '100% cotton', 'Quick drying'],
   '[]'::jsonb),
  ('non-slip-bath-mat', 'Non-Slip Bath Mat', 'Nest & Co', 'home', 13.99, null, 4.0, 71, 85, 201, false, '{}',
   'Memory foam mat that dries fast and grips tiles.',
   array['Non-slip base', 'Quick drying', 'Machine washable'],
   '[]'::jsonb),
  ('shower-curtain-with-hooks', 'Shower Curtain with Hooks', 'Nest & Co', 'home', 14.99, 19.94, 3.9, 183, 97, 202, true, '{}',
   'Water-repellent curtain with weighted hem and 12 rust-proof hooks.',
   array['180 x 180cm', 'Water repellent', '12 hooks'],
   '[]'::jsonb),
  ('laundry-basket-with-lid-60l', 'Laundry Basket with Lid, 60L', 'Nest & Co', 'home', 18.99, null, 4.0, 1239, 61, 203, false, '{}',
   'Collapsible hamper with carry handles.',
   array['60L', 'Collapsible', 'Breathable sides'],
   '[]'::jsonb),
  ('foldable-clothes-airer', 'Foldable Clothes Airer', 'Nest & Co', 'home', 27.99, 37.99, 4.9, 40, 105, 204, false, '{}',
   'Two-tier drying rack that folds flat for storage.',
   array['Two-tier', 'Folds flat', 'Holds 15kg'],
   '[]'::jsonb),
  ('steam-iron-2400w', 'Steam Iron, 2400W', 'Kitchenly', 'home', 34.99, 43.99, 4.0, 893, 111, 205, false, '{}',
   'Ceramic soleplate iron with vertical steam and self-clean.',
   array['2400W', 'Ceramic soleplate', 'Anti-drip'],
   '[]'::jsonb),
  ('handheld-garment-steamer', 'Handheld Garment Steamer', 'Kitchenly', 'home', 29.99, null, 4.4, 329, 70, 206, true, '{}',
   'Quick-heat travel steamer that removes creases from clothes and curtains.',
   array['Heats in 30 sec', '250ml tank', 'Compact'],
   '[]'::jsonb),
  ('cordless-stick-vacuum-cleaner', 'Cordless Stick Vacuum Cleaner', 'Cleanwave', 'home', 129, 152.99, 4.8, 218, 81, 207, false, '{}',
   'Lightweight cordless vacuum with 40 minutes run time and HEPA filtration.',
   array['40-minute runtime', 'HEPA filter', 'Wall dock'],
   '[]'::jsonb),
  ('robot-vacuum-with-mapping', 'Robot Vacuum with Mapping', 'Cleanwave', 'home', 199, 234.99, 4.2, 395, 59, 208, false, '{}',
   'Maps your home, avoids obstacles and returns to charge on its own.',
   array['Smart mapping', 'Auto recharge', 'App control'],
   '[]'::jsonb),
  ('bagless-cylinder-vacuum-800w', 'Bagless Cylinder Vacuum, 800W', 'Cleanwave', 'home', 79.99, null, 4.3, 233, 59, 209, false, '{}',
   'Powerful corded vacuum with a 2L dust cup and telescopic tube.',
   array['800W', '2L dust cup', 'Washable filter'],
   '[]'::jsonb),
  ('steam-mop-with-floor-pads', 'Steam Mop with Floor Pads', 'Cleanwave', 'home', 54.99, null, 4.7, 1081, 35, 210, false, '{}',
   'Sanitises hard floors with steam and no chemicals.',
   array['Chemical free', 'Fast heat-up', '2 microfibre pads'],
   '[]'::jsonb),
  ('microfibre-cleaning-cloths-24-pack', 'Microfibre Cleaning Cloths (24 pack)', 'Cleanwave', 'home', 12.99, null, 4.0, 1113, 33, 211, false, '{}',
   'Streak-free cloths for glass, kitchen and bathrooms.',
   array['24 pack', 'Lint free', 'Machine washable'],
   '[]'::jsonb),
  ('pedal-bin-30l-stainless-steel', 'Pedal Bin, 30L Stainless Steel', 'Nest & Co', 'home', 32.99, null, 3.9, 374, 113, 212, false, '{}',
   'Soft-close pedal bin with a removable inner bucket.',
   array['30L', 'Soft close', 'Fingerprint resistant'],
   '[]'::jsonb),
  ('under-bed-storage-boxes-4-pack', 'Under-Bed Storage Boxes (4 pack)', 'Nest & Co', 'home', 24.99, 33.99, 4.3, 492, 68, 213, true, '{}',
   'Zip-top storage boxes on wheels for extra space.',
   array['4 pack', 'Clear window', 'Reinforced handles'],
   '[]'::jsonb),
  ('wooden-wall-shelves-set-of-3', 'Wooden Wall Shelves (Set of 3)', 'Nest & Co', 'home', 29.99, 37.99, 4.3, 80, 59, 214, false, '{}',
   'Floating shelves in three sizes with hidden brackets.',
   array['3 sizes', 'Hidden brackets', 'Holds 10kg each'],
   '[]'::jsonb),
  ('floor-lamp-with-adjustable-arm', 'Floor Lamp with Adjustable Arm', 'Nest & Co', 'home', 49.99, null, 4.5, 247, 43, 215, false, '{}',
   'Matt black arched lamp with a fabric shade and foot switch.',
   array['Adjustable arm', 'E27 bulb', 'Foot switch'],
   '[]'::jsonb),
  ('led-desk-lamp-with-wireless-charger', 'LED Desk Lamp with Wireless Charger', 'Nest & Co', 'home', 36.99, 43.99, 4.4, 347, 102, 216, false, '{}',
   'Dimmable desk lamp with a Qi charging base and USB port.',
   array['5 brightness levels', 'Wireless charging', 'Eye-care light'],
   '[]'::jsonb),
  ('wall-clock-silent-sweep-30cm', 'Wall Clock, Silent Sweep, 30cm', 'Nest & Co', 'home', 17.99, null, 4.2, 70, 69, 217, false, '{}',
   'A minimalist round clock that ticks silently.',
   array['Silent movement', '30cm face', 'Easy to read'],
   '[]'::jsonb),
  ('framed-wall-art-set-3-piece', 'Framed Wall Art Set (3 piece)', 'Nest & Co', 'home', 34.99, null, 4.9, 48, 49, 218, false, '{}',
   'Abstract prints in black frames, ready to hang.',
   array['3 frames', 'Ready to hang', 'Matte finish'],
   '[]'::jsonb),
  ('decorative-cushions-with-covers-4-pack', 'Decorative Cushions with Covers (4 pack)', 'Nest & Co', 'home', 27.99, null, 4.6, 940, 37, 219, false, '{}',
   'Textured covers with soft inserts in earthy tones.',
   array['45 x 45cm', 'Zip covers', 'Inserts included'],
   '[]'::jsonb),
  ('ceramic-dinner-set-16-piece', 'Ceramic Dinner Set (16 piece)', 'Nest & Co', 'home', 59.99, 79.99, 3.9, 353, 82, 220, false, '{}',
   'Reactive-glaze plates and bowls for four.',
   array['Service for 4', 'Dishwasher safe', 'Microwave safe'],
   '[]'::jsonb),
  ('wine-glasses-set-of-6', 'Wine Glasses (Set of 6)', 'Nest & Co', 'home', 22.99, null, 4.0, 305, 117, 221, false, '{}',
   'Clear crystal-style glasses with slim stems.',
   array['Set of 6', 'Dishwasher safe', '350ml'],
   '[]'::jsonb),
  ('scented-candle-trio', 'Scented Candle Trio', 'Nest & Co', 'home', 19.99, 24.99, 4.5, 1592, 118, 222, false, '{}',
   'Three soy-wax candles: vanilla, cedar and fig.',
   array['Soy wax', '40-hour burn', 'Glass jars'],
   '[]'::jsonb),
  ('electric-fan-heater-2000w', 'Electric Fan Heater, 2000W', 'Warmly', 'home', 34.99, null, 4.1, 24, 78, 223, false, '{}',
   'Compact heater with a thermostat and overheat protection.',
   array['2000W', 'Thermostat', 'Tip-over protection'],
   '[]'::jsonb),
  ('pedestal-fan-16-oscillating', 'Pedestal Fan, 16" Oscillating', 'Warmly', 'home', 42.99, 53.99, 4.8, 237, 44, 224, false, '{}',
   'Height-adjustable fan with a quiet motor and three speeds.',
   array['16" blades', 'Oscillating', '3 speeds'],
   '[]'::jsonb),
  ('dehumidifier-12l-per-day', 'Dehumidifier, 12L per Day', 'Warmly', 'home', 139, null, 4.2, 1458, 94, 225, false, '{}',
   'Fights damp and mould, and dries laundry indoors.',
   array['12L per day', 'Auto shut-off', 'Laundry mode'],
   '[]'::jsonb),
  ('cordless-drill-driver-kit', 'Cordless Drill Driver Kit', 'Toolbox', 'home', 69.99, null, 4.1, 891, 9, 226, true, '{}',
   '18V drill with two batteries, charger and 30-piece bit set.',
   array['18V', '2 batteries', '30-piece bit set'],
   '[]'::jsonb),
  ('home-tool-kit-65-piece', 'Home Tool Kit (65 piece)', 'Toolbox', 'home', 39.99, 49.99, 4.6, 1465, 8, 227, false, '{}',
   'Hammer, pliers, screwdrivers and more in a carry case.',
   array['65 pieces', 'Carry case', 'Chrome vanadium'],
   '[]'::jsonb),
  ('folding-step-ladder-3-step', 'Folding Step Ladder, 3-Step', 'Toolbox', 'home', 29.99, null, 4.2, 267, 3, 228, false, '{}',
   'Steel step stool with a non-slip platform.',
   array['Holds 150kg', 'Non-slip steps', 'Folds flat'],
   '[]'::jsonb),
  ('garden-hose-with-spray-gun-25m', 'Garden Hose with Spray Gun, 25m', 'Toolbox', 'home', 26.99, null, 4.4, 370, 52, 229, false, '{}',
   'Kink-resistant hose with a 7-pattern spray nozzle.',
   array['25m', 'Kink resistant', '7 spray patterns'],
   '[]'::jsonb),
  ('slim-fit-chino-trousers', 'Slim Fit Chino Trousers', 'Basics Lab', 'fashion', 32.99, null, 4.9, 1254, 42, 230, false, '{}',
   'Stretch-cotton chinos with a tapered leg that go from office to weekend.',
   array['98% cotton, 2% elastane', 'Slim fit', 'Four pockets'],
   '[{"name": "Waist", "options": [{"label": "30"}, {"label": "32"}, {"label": "34"}, {"label": "36"}, {"label": "38"}]}, {"name": "Colour", "options": [{"label": "Indigo"}, {"label": "Black"}, {"label": "Stone"}]}]'::jsonb),
  ('straight-leg-denim-jeans', 'Straight Leg Denim Jeans', 'Denim Yard', 'fashion', 39.99, 47.99, 4.0, 986, 32, 231, false, '{}',
   'Classic mid-rise straight jeans in durable washed denim.',
   array['Mid rise', 'Non-stretch heritage denim', 'Five pockets'],
   '[{"name": "Waist", "options": [{"label": "30"}, {"label": "32"}, {"label": "34"}, {"label": "36"}, {"label": "38"}]}, {"name": "Colour", "options": [{"label": "Indigo"}, {"label": "Black"}, {"label": "Stone"}]}]'::jsonb),
  ('skinny-stretch-jeans', 'Skinny Stretch Jeans', 'Denim Yard', 'fashion', 36.99, null, 4.6, 1220, 51, 232, false, '{}',
   'Flexible skinny jeans that keep their shape.',
   array['Stretch denim', 'Skinny fit', 'Fade resistant'],
   '[{"name": "Waist", "options": [{"label": "30"}, {"label": "32"}, {"label": "34"}, {"label": "36"}, {"label": "38"}]}, {"name": "Colour", "options": [{"label": "Indigo"}, {"label": "Black"}, {"label": "Stone"}]}]'::jsonb),
  ('cargo-joggers', 'Cargo Joggers', 'Basics Lab', 'fashion', 29.99, 39.99, 4.4, 170, 5, 233, false, '{}',
   'Relaxed cargo joggers with a drawcord waist and cuffed ankles.',
   array['Six pockets', 'Elastic cuffs', 'Cotton twill'],
   '[{"name": "Size", "options": [{"label": "S"}, {"label": "M"}, {"label": "L"}, {"label": "XL"}]}, {"name": "Colour", "options": [{"label": "Black"}, {"label": "Navy"}, {"label": "Olive"}]}]'::jsonb),
  ('cotton-polo-shirt', 'Cotton Polo Shirt', 'Basics Lab', 'fashion', 19.99, null, 4.6, 68, 67, 234, false, '{}',
   'Breathable piqué polo with a two-button placket.',
   array['Piqué cotton', 'Regular fit', 'Ribbed collar'],
   '[{"name": "Size", "options": [{"label": "S"}, {"label": "M"}, {"label": "L"}, {"label": "XL"}]}, {"name": "Colour", "options": [{"label": "Black"}, {"label": "Navy"}, {"label": "Olive"}]}]'::jsonb),
  ('oxford-button-down-shirt', 'Oxford Button-Down Shirt', 'Heritage', 'fashion', 34.99, 43.99, 4.7, 54, 36, 235, false, '{}',
   'Textured Oxford cotton shirt with a button-down collar.',
   array['100% cotton', 'Regular fit', 'Chest pocket'],
   '[{"name": "Size", "options": [{"label": "S"}, {"label": "M"}, {"label": "L"}, {"label": "XL"}]}, {"name": "Colour", "options": [{"label": "Black"}, {"label": "Navy"}, {"label": "Olive"}]}]'::jsonb),
  ('linen-blend-summer-shirt', 'Linen Blend Summer Shirt', 'Heritage', 'fashion', 29.99, 39.99, 4.4, 1476, 28, 236, false, '{}',
   'Lightweight linen-blend shirt that stays cool in the heat.',
   array['Linen-cotton blend', 'Relaxed fit', 'Breathable'],
   '[{"name": "Size", "options": [{"label": "S"}, {"label": "M"}, {"label": "L"}, {"label": "XL"}]}, {"name": "Colour", "options": [{"label": "Black"}, {"label": "Navy"}, {"label": "Olive"}]}]'::jsonb),
  ('crewneck-sweatshirt', 'Crewneck Sweatshirt', 'Basics Lab', 'fashion', 27.99, null, 4.7, 51, 77, 237, false, '{}',
   'Brushed-back fleece sweatshirt with a ribbed neck and cuffs.',
   array['Brushed fleece', 'Relaxed fit', 'Machine washable'],
   '[{"name": "Size", "options": [{"label": "S"}, {"label": "M"}, {"label": "L"}, {"label": "XL"}]}, {"name": "Colour", "options": [{"label": "Black"}, {"label": "Navy"}, {"label": "Olive"}]}]'::jsonb),
  ('pullover-hoodie', 'Pullover Hoodie', 'Basics Lab', 'fashion', 34.99, 39.99, 4.0, 302, 77, 238, false, '{}',
   'Heavyweight hoodie with a lined hood and a kangaroo pocket.',
   array['380gsm fleece', 'Lined hood', 'Kangaroo pocket'],
   '[{"name": "Size", "options": [{"label": "S"}, {"label": "M"}, {"label": "L"}, {"label": "XL"}]}, {"name": "Colour", "options": [{"label": "Black"}, {"label": "Navy"}, {"label": "Olive"}]}]'::jsonb),
  ('zip-up-track-jacket', 'Zip-Up Track Jacket', 'Stride', 'fashion', 39.99, null, 4.2, 375, 76, 239, false, '{}',
   'Lightweight track jacket with zip pockets for training and travel.',
   array['Moisture wicking', 'Zip pockets', 'Slim fit'],
   '[{"name": "Size", "options": [{"label": "S"}, {"label": "M"}, {"label": "L"}, {"label": "XL"}]}, {"name": "Colour", "options": [{"label": "Black"}, {"label": "Navy"}, {"label": "Olive"}]}]'::jsonb),
  ('puffer-jacket-water-resistant', 'Puffer Jacket, Water-Resistant', 'Stride', 'fashion', 79.99, null, 4.6, 303, 26, 240, false, '{}',
   'Warm quilted puffer with a packable design and a stand collar.',
   array['Water resistant', 'Lightweight fill', 'Packs into pocket'],
   '[{"name": "Size", "options": [{"label": "S"}, {"label": "M"}, {"label": "L"}, {"label": "XL"}]}, {"name": "Colour", "options": [{"label": "Black"}, {"label": "Navy"}, {"label": "Olive"}]}]'::jsonb),
  ('waterproof-rain-jacket', 'Waterproof Rain Jacket', 'Stride', 'fashion', 59.99, null, 4.7, 73, 95, 241, false, '{}',
   'Taped-seam shell with an adjustable hood for wet-weather walks.',
   array['Waterproof 10000mm', 'Taped seams', 'Adjustable hood'],
   '[{"name": "Size", "options": [{"label": "S"}, {"label": "M"}, {"label": "L"}, {"label": "XL"}]}, {"name": "Colour", "options": [{"label": "Black"}, {"label": "Navy"}, {"label": "Olive"}]}]'::jsonb),
  ('wool-blend-overcoat', 'Wool Blend Overcoat', 'Heritage', 'fashion', 119, null, 4.5, 14, 104, 242, false, '{}',
   'Tailored single-breasted overcoat in a warm wool blend.',
   array['60% wool', 'Fully lined', 'Notch lapel'],
   '[{"name": "Size", "options": [{"label": "S"}, {"label": "M"}, {"label": "L"}, {"label": "XL"}]}, {"name": "Colour", "options": [{"label": "Black"}, {"label": "Navy"}, {"label": "Olive"}]}]'::jsonb),
  ('denim-trucker-jacket', 'Denim Trucker Jacket', 'Denim Yard', 'fashion', 54.99, null, 4.0, 1372, 14, 243, false, '{}',
   'Timeless trucker jacket in rigid indigo denim.',
   array['Rigid denim', 'Button front', 'Chest pockets'],
   '[{"name": "Size", "options": [{"label": "S"}, {"label": "M"}, {"label": "L"}, {"label": "XL"}]}, {"name": "Colour", "options": [{"label": "Black"}, {"label": "Navy"}, {"label": "Olive"}]}]'::jsonb),
  ('merino-wool-sweater', 'Merino Wool Sweater', 'Heritage', 'fashion', 49.99, null, 4.3, 1227, 120, 244, false, '{}',
   'Soft merino crewneck that stays warm without bulk.',
   array['100% merino wool', 'Machine washable', 'Ribbed trims'],
   '[{"name": "Size", "options": [{"label": "S"}, {"label": "M"}, {"label": "L"}, {"label": "XL"}]}, {"name": "Colour", "options": [{"label": "Black"}, {"label": "Navy"}, {"label": "Olive"}]}]'::jsonb),
  ('knit-cardigan', 'Knit Cardigan', 'Heritage', 'fashion', 42.99, 50.99, 4.4, 226, 52, 245, false, '{}',
   'Chunky knit button cardigan with patch pockets.',
   array['Soft acrylic-wool blend', 'Button front', 'Patch pockets'],
   '[{"name": "Size", "options": [{"label": "S"}, {"label": "M"}, {"label": "L"}, {"label": "XL"}]}, {"name": "Colour", "options": [{"label": "Black"}, {"label": "Navy"}, {"label": "Olive"}]}]'::jsonb),
  ('long-sleeve-thermal-top', 'Long Sleeve Thermal Top', 'Basics Lab', 'fashion', 16.99, null, 4.4, 1584, 114, 246, false, '{}',
   'Base-layer top with a waffle-knit texture for cold days.',
   array['Waffle knit', 'Body-hugging', 'Soft touch'],
   '[{"name": "Size", "options": [{"label": "S"}, {"label": "M"}, {"label": "L"}, {"label": "XL"}]}, {"name": "Colour", "options": [{"label": "Black"}, {"label": "Navy"}, {"label": "Olive"}]}]'::jsonb),
  ('athletic-performance-t-shirt', 'Athletic Performance T-Shirt', 'Stride', 'fashion', 18.99, null, 4.1, 202, 50, 247, false, '{}',
   'Quick-dry tee with flat seams and a reflective logo.',
   array['Quick dry', 'Flat seams', 'Reflective details'],
   '[{"name": "Size", "options": [{"label": "S"}, {"label": "M"}, {"label": "L"}, {"label": "XL"}]}, {"name": "Colour", "options": [{"label": "Black"}, {"label": "Navy"}, {"label": "Olive"}]}]'::jsonb),
  ('training-shorts-with-zip-pocket', 'Training Shorts with Zip Pocket', 'Stride', 'fashion', 22.99, null, 4.6, 222, 113, 248, false, '{}',
   'Lightweight running shorts with a zip pocket for keys.',
   array['Breathable mesh', 'Zip pocket', 'Elastic waist'],
   '[{"name": "Size", "options": [{"label": "S"}, {"label": "M"}, {"label": "L"}, {"label": "XL"}]}, {"name": "Colour", "options": [{"label": "Black"}, {"label": "Navy"}, {"label": "Olive"}]}]'::jsonb),
  ('compression-leggings', 'Compression Leggings', 'Stride', 'fashion', 29.99, 39.99, 4.8, 58, 48, 249, false, '{}',
   'High-waist leggings with a squat-proof fabric and a hidden pocket.',
   array['Squat proof', 'Hidden pocket', 'High waist'],
   '[{"name": "Size", "options": [{"label": "S"}, {"label": "M"}, {"label": "L"}, {"label": "XL"}]}, {"name": "Colour", "options": [{"label": "Black"}, {"label": "Navy"}, {"label": "Olive"}]}]'::jsonb),
  ('yoga-sports-bra', 'Yoga Sports Bra', 'Stride', 'fashion', 21.99, 29.99, 4.6, 613, 83, 250, false, '{}',
   'Medium-support bra with removable pads and a racerback.',
   array['Medium support', 'Removable pads', 'Racerback'],
   '[{"name": "Size", "options": [{"label": "S"}, {"label": "M"}, {"label": "L"}, {"label": "XL"}]}, {"name": "Colour", "options": [{"label": "Black"}, {"label": "Navy"}, {"label": "Olive"}]}]'::jsonb),
  ('floral-wrap-midi-dress', 'Floral Wrap Midi Dress', 'Willow & Rose', 'fashion', 44.99, 53.99, 4.1, 75, 6, 251, false, '{}',
   'Flowing wrap dress with a flattering V-neck and tie waist.',
   array['Wrap style', 'Lightweight viscose', 'Midi length'],
   '[{"name": "Size", "options": [{"label": "S"}, {"label": "M"}, {"label": "L"}, {"label": "XL"}]}, {"name": "Colour", "options": [{"label": "Black"}, {"label": "Navy"}, {"label": "Olive"}]}]'::jsonb),
  ('casual-shirt-dress', 'Casual Shirt Dress', 'Willow & Rose', 'fashion', 39.99, null, 4.6, 25, 72, 252, false, '{}',
   'Button-front shirt dress with a belt in soft cotton poplin.',
   array['Cotton poplin', 'Belt included', 'Side pockets'],
   '[{"name": "Size", "options": [{"label": "S"}, {"label": "M"}, {"label": "L"}, {"label": "XL"}]}, {"name": "Colour", "options": [{"label": "Black"}, {"label": "Navy"}, {"label": "Olive"}]}]'::jsonb),
  ('pleated-maxi-skirt', 'Pleated Maxi Skirt', 'Willow & Rose', 'fashion', 32.99, 41.99, 4.2, 90, 41, 253, false, '{}',
   'Flowy pleated skirt with an elastic waist.',
   array['Pleated', 'Elastic waist', 'Fully lined'],
   '[{"name": "Size", "options": [{"label": "S"}, {"label": "M"}, {"label": "L"}, {"label": "XL"}]}, {"name": "Colour", "options": [{"label": "Black"}, {"label": "Navy"}, {"label": "Olive"}]}]'::jsonb),
  ('high-waisted-wide-leg-trousers', 'High-Waisted Wide-Leg Trousers', 'Willow & Rose', 'fashion', 37.99, null, 4.8, 30, 62, 254, false, '{}',
   'Fluid wide-leg trousers with a tailored waist.',
   array['High rise', 'Wide leg', 'Side pockets'],
   '[{"name": "Size", "options": [{"label": "S"}, {"label": "M"}, {"label": "L"}, {"label": "XL"}]}, {"name": "Colour", "options": [{"label": "Black"}, {"label": "Navy"}, {"label": "Olive"}]}]'::jsonb),
  ('satin-blouse', 'Satin Blouse', 'Willow & Rose', 'fashion', 28.99, 36.99, 4.8, 1363, 54, 255, false, '{}',
   'Smooth satin blouse with a relaxed drape.',
   array['Satin finish', 'Relaxed fit', 'Button cuffs'],
   '[{"name": "Size", "options": [{"label": "S"}, {"label": "M"}, {"label": "L"}, {"label": "XL"}]}, {"name": "Colour", "options": [{"label": "Black"}, {"label": "Navy"}, {"label": "Olive"}]}]'::jsonb),
  ('silk-feel-scarf', 'Silk-Feel Scarf', 'Willow & Rose', 'fashion', 14.99, null, 4.4, 128, 115, 256, true, '{}',
   'Lightweight printed scarf that dresses up any outfit.',
   array['90 x 90cm', 'Soft satin', 'Multiple ways to wear'],
   '[{"name": "Colour", "options": [{"label": "Black"}, {"label": "Tan"}, {"label": "Navy"}]}]'::jsonb),
  ('white-leather-sneakers', 'White Leather Sneakers', 'Stride', 'fashion', 64.99, 86.99, 4.5, 67, 84, 257, false, '{}',
   'Minimal leather sneakers with a cushioned insole.',
   array['Genuine leather', 'Cushioned insole', 'Vulcanised sole'],
   '[{"name": "Size (EU)", "options": [{"label": "39"}, {"label": "40"}, {"label": "41"}, {"label": "42"}, {"label": "43"}, {"label": "44"}, {"label": "45"}, {"label": "46"}]}]'::jsonb),
  ('canvas-low-top-trainers', 'Canvas Low-Top Trainers', 'Stride', 'fashion', 34.99, 46.99, 4.7, 227, 35, 258, false, '{}',
   'Everyday canvas trainers with a rubber toe cap.',
   array['Cotton canvas', 'Cushioned insole', 'Rubber sole'],
   '[{"name": "Size (EU)", "options": [{"label": "39"}, {"label": "40"}, {"label": "41"}, {"label": "42"}, {"label": "43"}, {"label": "44"}, {"label": "45"}, {"label": "46"}]}]'::jsonb),
  ('high-top-basketball-sneakers', 'High-Top Basketball Sneakers', 'Stride', 'fashion', 84.99, null, 4.8, 8, 46, 259, false, '{}',
   'Supportive high-tops with responsive cushioning and grippy outsoles.',
   array['Ankle support', 'Responsive cushioning', 'Grippy outsole'],
   '[{"name": "Size (EU)", "options": [{"label": "39"}, {"label": "40"}, {"label": "41"}, {"label": "42"}, {"label": "43"}, {"label": "44"}, {"label": "45"}, {"label": "46"}]}]'::jsonb),
  ('trail-running-shoes', 'Trail Running Shoes', 'Stride', 'fashion', 74.99, null, 4.6, 193, 19, 260, false, '{}',
   'Rugged trail shoes with aggressive lugs and a rock plate.',
   array['Aggressive lugs', 'Rock plate', 'Breathable mesh'],
   '[{"name": "Size (EU)", "options": [{"label": "39"}, {"label": "40"}, {"label": "41"}, {"label": "42"}, {"label": "43"}, {"label": "44"}, {"label": "45"}, {"label": "46"}]}]'::jsonb),
  ('leather-chelsea-boots', 'Leather Chelsea Boots', 'Heritage', 'fashion', 89.99, null, 4.1, 72, 49, 261, false, '{}',
   'Polished leather boots with elastic side panels.',
   array['Genuine leather', 'Elastic gussets', 'Rubber sole'],
   '[{"name": "Size (EU)", "options": [{"label": "39"}, {"label": "40"}, {"label": "41"}, {"label": "42"}, {"label": "43"}, {"label": "44"}, {"label": "45"}, {"label": "46"}]}]'::jsonb),
  ('suede-desert-boots', 'Suede Desert Boots', 'Heritage', 'fashion', 69.99, 82.99, 4.4, 370, 72, 262, false, '{}',
   'Classic suede desert boots with a crepe-style sole.',
   array['Soft suede', 'Lace-up', 'Cushioned insole'],
   '[{"name": "Size (EU)", "options": [{"label": "39"}, {"label": "40"}, {"label": "41"}, {"label": "42"}, {"label": "43"}, {"label": "44"}, {"label": "45"}, {"label": "46"}]}]'::jsonb),
  ('leather-oxford-dress-shoes', 'Leather Oxford Dress Shoes', 'Heritage', 'fashion', 94.99, null, 4.7, 367, 102, 263, false, '{}',
   'Polished lace-up dress shoes for the office and formal events.',
   array['Genuine leather', 'Goodyear-style sole', 'Padded collar'],
   '[{"name": "Size (EU)", "options": [{"label": "39"}, {"label": "40"}, {"label": "41"}, {"label": "42"}, {"label": "43"}, {"label": "44"}, {"label": "45"}, {"label": "46"}]}]'::jsonb),
  ('slip-on-loafers', 'Slip-On Loafers', 'Heritage', 'fashion', 54.99, null, 4.0, 614, 33, 264, false, '{}',
   'Soft leather loafers that go with everything.',
   array['Leather upper', 'Slip on', 'Flexible sole'],
   '[{"name": "Size (EU)", "options": [{"label": "39"}, {"label": "40"}, {"label": "41"}, {"label": "42"}, {"label": "43"}, {"label": "44"}, {"label": "45"}, {"label": "46"}]}]'::jsonb),
  ('ankle-boots-with-block-heel', 'Ankle Boots with Block Heel', 'Willow & Rose', 'fashion', 64.99, null, 4.0, 34, 69, 265, false, '{}',
   'Stylish ankle boots with a stable block heel and side zip.',
   array['Side zip', 'Block heel', 'Faux suede'],
   '[{"name": "Size (EU)", "options": [{"label": "39"}, {"label": "40"}, {"label": "41"}, {"label": "42"}, {"label": "43"}, {"label": "44"}, {"label": "45"}, {"label": "46"}]}]'::jsonb),
  ('comfort-sandals-with-arch-support', 'Comfort Sandals with Arch Support', 'Stride', 'fashion', 29.99, null, 4.4, 318, 115, 266, false, '{}',
   'Adjustable straps and a cushioned footbed for all-day wear.',
   array['Arch support', 'Adjustable straps', 'Non-slip sole'],
   '[{"name": "Size (EU)", "options": [{"label": "39"}, {"label": "40"}, {"label": "41"}, {"label": "42"}, {"label": "43"}, {"label": "44"}, {"label": "45"}, {"label": "46"}]}]'::jsonb),
  ('rubber-slides', 'Rubber Slides', 'Stride', 'fashion', 14.99, 18.74, 4.7, 35, 101, 267, true, '{}',
   'Lightweight slides for beach, pool and after training.',
   array['Quick dry', 'Cushioned footbed', 'Lightweight'],
   '[{"name": "Size (EU)", "options": [{"label": "39"}, {"label": "40"}, {"label": "41"}, {"label": "42"}, {"label": "43"}, {"label": "44"}, {"label": "45"}, {"label": "46"}]}]'::jsonb),
  ('leather-belt-reversible', 'Leather Belt, Reversible', 'Heritage', 'fashion', 22.99, null, 4.8, 301, 110, 268, false, '{}',
   'Black-and-brown reversible belt with a rotating buckle.',
   array['Genuine leather', 'Reversible', 'Rotating buckle'],
   '[]'::jsonb),
  ('bifold-leather-wallet', 'Bifold Leather Wallet', 'Heritage', 'fashion', 24.99, null, 4.6, 251, 60, 269, false, '{}',
   'Slim RFID-blocking wallet with six card slots.',
   array['RFID blocking', '6 card slots', 'Genuine leather'],
   '[]'::jsonb),
  ('canvas-backpack-25l', 'Canvas Backpack, 25L', 'Stride', 'fashion', 39.99, null, 4.6, 128, 80, 270, false, '{}',
   'Roomy backpack with a padded laptop pocket and side bottle holders.',
   array['Fits 15" laptop', 'Water-resistant canvas', 'Padded straps'],
   '[{"name": "Colour", "options": [{"label": "Black"}, {"label": "Tan"}, {"label": "Navy"}]}]'::jsonb),
  ('crossbody-bag', 'Crossbody Bag', 'Willow & Rose', 'fashion', 34.99, 41.99, 4.7, 1148, 66, 271, false, '{}',
   'Compact vegan-leather crossbody with an adjustable strap.',
   array['Vegan leather', 'Adjustable strap', 'Zip closure'],
   '[{"name": "Colour", "options": [{"label": "Black"}, {"label": "Tan"}, {"label": "Navy"}]}]'::jsonb),
  ('tote-bag-everyday-canvas', 'Tote Bag, Everyday Canvas', 'Willow & Rose', 'fashion', 16.99, null, 4.1, 52, 104, 272, false, '{}',
   'Sturdy canvas tote with an inner zip pocket.',
   array['Heavy canvas', 'Inner zip pocket', 'Long handles'],
   '[{"name": "Colour", "options": [{"label": "Black"}, {"label": "Tan"}, {"label": "Navy"}]}]'::jsonb),
  ('wool-beanie-hat', 'Wool Beanie Hat', 'Heritage', 'fashion', 12.99, 17.28, 4.5, 10, 16, 273, false, '{}',
   'Warm ribbed beanie in soft wool-blend knit.',
   array['Wool blend', 'One size', 'Fleece lined'],
   '[{"name": "Colour", "options": [{"label": "Black"}, {"label": "Tan"}, {"label": "Navy"}]}]'::jsonb),
  ('baseball-cap-adjustable', 'Baseball Cap, Adjustable', 'Basics Lab', 'fashion', 13.99, null, 4.8, 82, 39, 274, false, '{}',
   'Six-panel cotton cap with a curved brim and metal buckle.',
   array['Cotton twill', 'Adjustable', 'Curved brim'],
   '[{"name": "Colour", "options": [{"label": "Black"}, {"label": "Tan"}, {"label": "Navy"}]}]'::jsonb),
  ('knitted-scarf-and-glove-set', 'Knitted Scarf and Glove Set', 'Heritage', 'fashion', 21.99, null, 4.0, 1698, 88, 275, false, '{}',
   'Matching scarf and touchscreen gloves in soft knit.',
   array['Touchscreen fingertips', 'Soft acrylic', 'One size'],
   '[{"name": "Colour", "options": [{"label": "Black"}, {"label": "Tan"}, {"label": "Navy"}]}]'::jsonb),
  ('sports-socks-6-pairs', 'Sports Socks (6 pairs)', 'Stride', 'fashion', 12.99, null, 4.1, 26, 47, 276, true, '{}',
   'Cushioned cotton-blend socks with arch support.',
   array['6 pairs', 'Cushioned sole', 'Arch support'],
   '[]'::jsonb),
  ('cotton-boxer-briefs-5-pack', 'Cotton Boxer Briefs (5 pack)', 'Basics Lab', 'fashion', 19.99, null, 4.8, 380, 18, 277, false, '{}',
   'Soft stretch cotton boxer briefs with a no-roll waistband.',
   array['5 pack', 'Stretch cotton', 'No-roll waistband'],
   '[{"name": "Size", "options": [{"label": "S"}, {"label": "M"}, {"label": "L"}, {"label": "XL"}]}, {"name": "Colour", "options": [{"label": "Black"}, {"label": "Navy"}, {"label": "Olive"}]}]'::jsonb),
  ('watch-chronograph-steel', 'Watch, Chronograph Steel', 'Heritage', 'fashion', 89.99, null, 4.6, 223, 50, 278, false, '{}',
   'Stainless steel chronograph with three sub-dials and a date window.',
   array['Chronograph', 'Water resistant 5ATM', 'Sapphire-coated glass'],
   '[]'::jsonb),
  ('minimalist-leather-strap-watch', 'Minimalist Leather Strap Watch', 'Heritage', 'fashion', 49.99, null, 4.4, 36, 19, 279, false, '{}',
   'Slim 40mm case, sunray dial and a genuine leather strap.',
   array['40mm case', 'Genuine leather strap', 'Japanese quartz'],
   '[]'::jsonb),
  ('stainless-steel-chain-necklace', 'Stainless Steel Chain Necklace', 'Willow & Rose', 'fashion', 17.99, null, 4.5, 258, 94, 280, true, '{}',
   'A layering-friendly stainless steel necklace that won''t tarnish.',
   array['Hypoallergenic', 'Tarnish resistant', 'Adjustable length'],
   '[]'::jsonb),
  ('pearl-stud-earrings', 'Pearl Stud Earrings', 'Willow & Rose', 'fashion', 14.99, null, 4.3, 157, 89, 281, false, '{}',
   'Freshwater-style pearls on sterling silver posts.',
   array['Sterling silver posts', 'Nickel free', 'Gift box'],
   '[]'::jsonb),
  ('aviator-sunglasses-polarised', 'Aviator Sunglasses, Polarised', 'Heritage', 'fashion', 27.99, null, 4.1, 346, 54, 282, false, '{}',
   'Classic metal aviators with polarised, UV400 lenses.',
   array['UV400', 'Polarised', 'Spring hinges'],
   '[]'::jsonb),
  ('pyjama-set-soft-cotton', 'Pyjama Set, Soft Cotton', 'Basics Lab', 'fashion', 28.99, null, 4.1, 120, 101, 283, false, '{}',
   'Long-sleeve pyjama set with piped trim and an elastic waist.',
   array['100% cotton', 'Piped trim', 'Elastic waist'],
   '[{"name": "Size", "options": [{"label": "S"}, {"label": "M"}, {"label": "L"}, {"label": "XL"}]}, {"name": "Colour", "options": [{"label": "Black"}, {"label": "Navy"}, {"label": "Olive"}]}]'::jsonb)
on conflict (id) do nothing;
